/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samson
 */
public class ConsultancyGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesGUI
     */
    int mousepX;
    int mousepY;
    String sid, nxtsid;
    BigDecimal amount, discount, netamount;
    
    public ConsultancyGUI() {
        initComponents();
        
        currentDate();
        loadTbl();
        
        
        
        
        sid = "";
        nxtsid = "";
        netamount = new BigDecimal("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_consultancycreate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_consultancycreateid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_consultancycreatepatientid = new javax.swing.JTextField();
        jTextField_consultancycreatedoctorid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_consultancycreatedate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_consultancycreatepatientname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_consultancycreatedoctorname = new javax.swing.JTextField();
        jButton_consultancycreatereset = new javax.swing.JButton();
        jButton_consultancycreateprint = new javax.swing.JButton();
        jButton_consultancycreatesave = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField_consultancycreateamount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_consultancycreatediscount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_consultancycreatenetamount = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jPanel_consultancyview = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_consultancyviewenterkey = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_consultancyview = new javax.swing.JTable();
        jButton_consultancyviewdelete = new javax.swing.JButton();
        jLabel_consultancyclose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(45, 120, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(45, 120, 230));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CONSULTANCY INFORMATION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 30, 440, -1));

        jTabbedPane1.setForeground(new java.awt.Color(50, 50, 50));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1180, 670));

        jPanel_consultancycreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_consultancycreate.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_consultancycreate.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_consultancycreate.setPreferredSize(new java.awt.Dimension(1180, 680));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Consultancy ID");

        jTextField_consultancycreateid.setEditable(false);
        jTextField_consultancycreateid.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_consultancycreateid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreateid.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_consultancycreateid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Doctor ID");

        jTextField_consultancycreatepatientid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatepatientid.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_consultancycreatepatientid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_consultancycreatepatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreatepatientidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreatepatientidKeyReleased(evt);
            }
        });

        jTextField_consultancycreatedoctorid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatedoctorid.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_consultancycreatedoctorid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_consultancycreatedoctorid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreatedoctoridKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreatedoctoridKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Date");

        jTextField_consultancycreatedate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatedate.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_consultancycreatedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Patient name");

        jTextField_consultancycreatepatientname.setEditable(false);
        jTextField_consultancycreatepatientname.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_consultancycreatepatientname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatepatientname.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_consultancycreatepatientname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Doctor name");

        jTextField_consultancycreatedoctorname.setEditable(false);
        jTextField_consultancycreatedoctorname.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_consultancycreatedoctorname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatedoctorname.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_consultancycreatedoctorname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton_consultancycreatereset.setBackground(new java.awt.Color(45, 120, 230));
        jButton_consultancycreatereset.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_consultancycreatereset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_consultancycreatereset.setText("RESET");
        jButton_consultancycreatereset.setAlignmentY(0.0F);
        jButton_consultancycreatereset.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_consultancycreatereset.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatereset.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatereset.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultancycreateresetActionPerformed(evt);
            }
        });

        jButton_consultancycreateprint.setBackground(new java.awt.Color(45, 120, 230));
        jButton_consultancycreateprint.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_consultancycreateprint.setForeground(new java.awt.Color(255, 255, 255));
        jButton_consultancycreateprint.setText("PRINT");
        jButton_consultancycreateprint.setAlignmentY(0.0F);
        jButton_consultancycreateprint.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_consultancycreateprint.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreateprint.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreateprint.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreateprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultancycreateprintActionPerformed(evt);
            }
        });

        jButton_consultancycreatesave.setBackground(new java.awt.Color(45, 120, 230));
        jButton_consultancycreatesave.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_consultancycreatesave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_consultancycreatesave.setText("SAVE");
        jButton_consultancycreatesave.setAlignmentY(0.0F);
        jButton_consultancycreatesave.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_consultancycreatesave.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatesave.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatesave.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_consultancycreatesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultancycreatesaveActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Amount");

        jTextField_consultancycreateamount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreateamount.setForeground(new java.awt.Color(0, 0, 150));
        jTextField_consultancycreateamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_consultancycreateamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreateamountKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel19.setText("Discount");

        jTextField_consultancycreatediscount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatediscount.setForeground(new java.awt.Color(0, 150, 0));
        jTextField_consultancycreatediscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_consultancycreatediscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_consultancycreatediscountKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setText("Net amount");

        jTextField_consultancycreatenetamount.setEditable(false);
        jTextField_consultancycreatenetamount.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_consultancycreatenetamount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancycreatenetamount.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_consultancycreatenetamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel34.setText("Create Consultancy");

        javax.swing.GroupLayout jPanel_consultancycreateLayout = new javax.swing.GroupLayout(jPanel_consultancycreate);
        jPanel_consultancycreate.setLayout(jPanel_consultancycreateLayout);
        jPanel_consultancycreateLayout.setHorizontalGroup(
            jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancycreateLayout.createSequentialGroup()
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_consultancycreatesave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_consultancycreateprint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_consultancycreatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancycreateLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_consultancycreatenetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancycreateLayout.createSequentialGroup()
                                                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_consultancycreatedate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextField_consultancycreatepatientname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField_consultancycreatedoctorname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                                .addComponent(jTextField_consultancycreateamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_consultancycreatediscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_consultancycreatedoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_consultancycreatepatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_consultancycreateid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(jPanel_consultancycreateLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(50, 50, 50))
        );
        jPanel_consultancycreateLayout.setVerticalGroup(
            jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancycreateLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel34)
                .addGap(50, 50, 50)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_consultancycreateid)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_consultancycreatedate))
                .addGap(40, 40, 40)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_consultancycreatepatientid)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_consultancycreatepatientname))
                .addGap(40, 40, 40)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_consultancycreatedoctorid)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_consultancycreatedoctorname))
                .addGap(40, 40, 40)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_consultancycreateamount)
                    .addComponent(jLabel19)
                    .addComponent(jTextField_consultancycreatediscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_consultancycreatenetamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel_consultancycreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_consultancycreatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_consultancycreateprint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_consultancycreatesave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("CREATE CONSULTANCY", jPanel_consultancycreate);

        jPanel_consultancyview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_consultancyview.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_consultancyview.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_consultancyview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_consultancyviewMouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel35.setText("View Consultancy");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel31.setText("Enter keyword");

        jTextField_consultancyviewenterkey.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_consultancyviewenterkey.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_consultancyviewenterkey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_consultancyviewenterkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_consultancyviewenterkeyKeyReleased(evt);
            }
        });

        jTable_consultancyview.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable_consultancyview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE", "PATIENT NAME", "DOCTOR NAME", "AMOUNT", "DISCOUNT", "NET AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_consultancyview.setSelectionBackground(new java.awt.Color(45, 120, 230));
        jScrollPane2.setViewportView(jTable_consultancyview);
        if (jTable_consultancyview.getColumnModel().getColumnCount() > 0) {
            jTable_consultancyview.getColumnModel().getColumn(1).setMinWidth(180);
            jTable_consultancyview.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTable_consultancyview.getColumnModel().getColumn(1).setMaxWidth(180);
        }

        jButton_consultancyviewdelete.setBackground(new java.awt.Color(45, 120, 230));
        jButton_consultancyviewdelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_consultancyviewdelete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_consultancyviewdelete.setText("DELETE");
        jButton_consultancyviewdelete.setAlignmentY(0.0F);
        jButton_consultancyviewdelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_consultancyviewdelete.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_consultancyviewdelete.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_consultancyviewdelete.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_consultancyviewdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultancyviewdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_consultancyviewLayout = new javax.swing.GroupLayout(jPanel_consultancyview);
        jPanel_consultancyview.setLayout(jPanel_consultancyviewLayout);
        jPanel_consultancyviewLayout.setHorizontalGroup(
            jPanel_consultancyviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancyviewLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(jPanel_consultancyviewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_consultancyviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_consultancyviewLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_consultancyviewLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_consultancyviewenterkey, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_consultancyviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel_consultancyviewLayout.setVerticalGroup(
            jPanel_consultancyviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_consultancyviewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel_consultancyviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_consultancyviewenterkey)
                    .addComponent(jButton_consultancyviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("  VIEW CONSULTANCY  ", jPanel_consultancyview);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1180, 670));

        jLabel_consultancyclose.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel_consultancyclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_consultancyclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_consultancyclose.setText("X");
        jLabel_consultancyclose.setAlignmentY(0.0F);
        jLabel_consultancyclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_consultancycloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_consultancyclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    MysqlConnection mc = new MysqlConnection();
    
    public void genId(){
        //CT000000
        try{
            ResultSet rs = mc.getData("SELECT id FROM consultancy ORDER BY id DESC LIMIT 1");
		if(rs.next()){
			String idval = rs.getString("id");
			int ln = idval.length();
			String stxt = idval.substring(0, 2);
			String snum = idval.substring(2, ln);
                        String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
			sid = stxt + num;
		}
		else{
			sid = "CT000001";
		}
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }
    
    public void setId(){
        int ln = sid.length();
        String stxt = sid.substring(0, 2);
	String snum = sid.substring(2, ln);
	String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
	nxtsid = stxt + num;
    }    
    
    public void currentDate(){
        Thread currentDate = new Thread(){
            public void run(){
                try{
                    for(;;){
                        Calendar clr = new GregorianCalendar();
                        int year = clr.get(Calendar.YEAR);
                        int month = clr.get(Calendar.MONTH);
                        month++; 
                        int day = clr.get(Calendar.DAY_OF_MONTH);
                        int hour = clr.get(Calendar.HOUR);
                        int minute = clr.get(Calendar.MINUTE);
                        int second = clr.get(Calendar.SECOND);
                        String syear = String.format("%04d", year);
                        String smonth = String.format("%02d", month);
                        String sday = String.format("%02d", day);
                        String shour = String.format("%02d", hour);
                        String sminute = String.format("%02d", minute);
                        String ssecond = String.format("%02d", second);
                        jTextField_consultancycreatedate.setText(syear + "-" + smonth + "-" + sday + " " + shour + ":" + sminute + ":" + ssecond);
                        sleep(1000);
                    }
                }
                catch(Exception exc){
                    exc.printStackTrace();
                }
            }
        };
        currentDate.start();
    }    
    
    public void netAmount(){
        if(!jTextField_consultancycreateamount.getText().isEmpty()){
            amount = new BigDecimal(jTextField_consultancycreateamount.getText());
        }
        else{
            amount = new BigDecimal("0.00");
        }
        if(!jTextField_consultancycreatediscount.getText().isEmpty()){
            discount = new BigDecimal(jTextField_consultancycreatediscount.getText());
        }
        else{
            discount = new BigDecimal("0.00");
        }
        netamount = amount.subtract(discount);
        jTextField_consultancycreatenetamount.setText(String.format("%.2f", netamount));
    }
    
    
    
    
    private void jLabel_consultancycloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_consultancycloseMouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel_consultancycloseMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jTextField_consultancycreatepatientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreatepatientidKeyReleased
        try{
            ResultSet rs = mc.getData("SELECT name FROM patient WHERE id = '"+jTextField_consultancycreatepatientid.getText()+"'");
            if(rs.first()){
                jTextField_consultancycreatepatientname.setText(rs.getString("name"));
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }//GEN-LAST:event_jTextField_consultancycreatepatientidKeyReleased

    private void jTextField_consultancycreatepatientidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreatepatientidKeyPressed
        jTextField_consultancycreatepatientname.setText(null);
    }//GEN-LAST:event_jTextField_consultancycreatepatientidKeyPressed

    private void jTextField_consultancycreatedoctoridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreatedoctoridKeyPressed
                jTextField_consultancycreatedoctorname.setText(null);
    }//GEN-LAST:event_jTextField_consultancycreatedoctoridKeyPressed

    private void jTextField_consultancycreatedoctoridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreatedoctoridKeyReleased
        try{
            ResultSet rs = mc.getData("SELECT name FROM doctor WHERE id = '"+jTextField_consultancycreatedoctorid.getText()+"'");
            if(rs.first()){
                jTextField_consultancycreatedoctorname.setText(rs.getString("name"));
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }//GEN-LAST:event_jTextField_consultancycreatedoctoridKeyReleased

    private void jTextField_consultancycreateamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreateamountKeyReleased
       //if(evt.getKeyCode() == 10){
           netAmount();
           //jTextField_consultancycreatediscount.grabFocus();
       //}
        
    }//GEN-LAST:event_jTextField_consultancycreateamountKeyReleased

    private void jTextField_consultancycreatediscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancycreatediscountKeyReleased
        netAmount();
    }//GEN-LAST:event_jTextField_consultancycreatediscountKeyReleased

    private void jButton_consultancycreatesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultancycreatesaveActionPerformed
        if(jTextField_consultancycreatedate.getText().isEmpty() || jTextField_consultancycreatepatientid.getText().isEmpty() || jTextField_consultancycreatepatientname.getText().isEmpty() || jTextField_consultancycreatedoctorid.getText().isEmpty() || jTextField_consultancycreatedoctorname.getText().isEmpty() || jTextField_consultancycreateamount.getText().isEmpty() || jTextField_consultancycreatediscount.getText().isEmpty() || jTextField_consultancycreatenetamount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
        else{
            try{
                genId();
                setId();
                mc.putData("INSERT INTO consultancy (id, patient, doctor, amount, discount, net_amount, date) VALUES ('"+sid+"', '"+jTextField_consultancycreatepatientid.getText()+"', '"+jTextField_consultancycreatedoctorid.getText()+"', '"+jTextField_consultancycreateamount.getText()+"', '"+jTextField_consultancycreatediscount.getText()+"', '"+jTextField_consultancycreatenetamount.getText()+"', '"+jTextField_consultancycreatedate.getText()+"')");
                jTextField_consultancycreateid.setText(nxtsid);
                jTextField_consultancycreatepatientid.setText(null);
                jTextField_consultancycreatepatientname.setText(null);
                jTextField_consultancycreatedoctorid.setText(null);
                jTextField_consultancycreatedoctorname.setText(null);
                jTextField_consultancycreateamount.setText(null);
                jTextField_consultancycreatediscount.setText(null);
                jTextField_consultancycreatenetamount.setText(null);
                jTextField_consultancycreatedate.setText(null);
                JOptionPane.showMessageDialog(null, "Data added");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        
        DefaultTableModel dtm = (DefaultTableModel)jTable_consultancyview.getModel();
        dtm.setRowCount(0);
        loadTbl();
    }//GEN-LAST:event_jButton_consultancycreatesaveActionPerformed

    private void jButton_consultancycreateresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultancycreateresetActionPerformed
        jTextField_consultancycreatepatientid.setText(null);
        jTextField_consultancycreatepatientname.setText(null);
        jTextField_consultancycreatedoctorid.setText(null);
        jTextField_consultancycreatedoctorname.setText(null);
        jTextField_consultancycreateamount.setText(null);
        jTextField_consultancycreatediscount.setText(null);
        jTextField_consultancycreatenetamount.setText(null);
        jTextField_consultancycreatedate.setText(null);
    }//GEN-LAST:event_jButton_consultancycreateresetActionPerformed

    private void jButton_consultancycreateprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultancycreateprintActionPerformed
        if(jTextField_consultancycreatedate.getText().isEmpty() || jTextField_consultancycreatepatientid.getText().isEmpty() || jTextField_consultancycreatepatientname.getText().isEmpty() || jTextField_consultancycreatedoctorid.getText().isEmpty() || jTextField_consultancycreatedoctorname.getText().isEmpty() || jTextField_consultancycreateamount.getText().isEmpty() || jTextField_consultancycreatediscount.getText().isEmpty() || jTextField_consultancycreatenetamount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
        else{
            try{
                genId();
                setId();
                mc.putData("INSERT INTO consultancy (id, patient, doctor, amount, discount, net_amount, date) VALUES ('"+sid+"', '"+jTextField_consultancycreatepatientid.getText()+"', '"+jTextField_consultancycreatedoctorid.getText()+"', '"+jTextField_consultancycreateamount.getText()+"', '"+jTextField_consultancycreatediscount.getText()+"', '"+jTextField_consultancycreatenetamount.getText()+"', '"+jTextField_consultancycreatedate.getText()+"')");
                jTextField_consultancycreateid.setText(nxtsid);
                jTextField_consultancycreatepatientid.setText(null);
                jTextField_consultancycreatepatientname.setText(null);
                jTextField_consultancycreatedoctorid.setText(null);
                jTextField_consultancycreatedoctorname.setText(null);
                jTextField_consultancycreateamount.setText(null);
                jTextField_consultancycreatediscount.setText(null);
                jTextField_consultancycreatenetamount.setText(null);
                jTextField_consultancycreatedate.setText(null);
                JOptionPane.showMessageDialog(null, "Data added");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        
        DefaultTableModel dtm = (DefaultTableModel)jTable_consultancyview.getModel();
        dtm.setRowCount(0);
        loadTbl();
        
        //PRINT
        
    }//GEN-LAST:event_jButton_consultancycreateprintActionPerformed

    private void jTextField_consultancyviewenterkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_consultancyviewenterkeyKeyReleased
        DefaultTableModel dtm = (DefaultTableModel)jTable_consultancyview.getModel();
        String search = jTextField_consultancyviewenterkey.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(dtm);
        jTable_consultancyview.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField_consultancyviewenterkeyKeyReleased

    private void jButton_consultancyviewdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultancyviewdeleteActionPerformed
        int sri[] = jTable_consultancyview.getSelectedRows();
        String sri_id[] = new String[sri.length];
        DefaultTableModel dtm = (DefaultTableModel)jTable_consultancyview.getModel();
        if(sri.length > 0){
            try{
                for(int i = sri.length - 1; i >= 0; i--){
                    sri_id[i] = jTable_consultancyview.getModel().getValueAt(sri[i], 0).toString();
                    Statement stmt = MysqlConnection.conn().createStatement();
                    stmt.executeUpdate("DELETE FROM consultancy WHERE id = '"+sri_id[i]+"'");
                    dtm.removeRow(sri[i]);
                }
                dtm.setRowCount(0);
                loadTbl();
                JOptionPane.showMessageDialog(null, "Data deleted successfully!");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to delete data!");
        }
    }//GEN-LAST:event_jButton_consultancyviewdeleteActionPerformed

    private void jPanel_consultancyviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_consultancyviewMouseClicked
        jTable_consultancyview.clearSelection();
    }//GEN-LAST:event_jPanel_consultancyviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultancyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultancyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultancyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultancyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultancyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_consultancycreateprint;
    private javax.swing.JButton jButton_consultancycreatereset;
    private javax.swing.JButton jButton_consultancycreatesave;
    private javax.swing.JButton jButton_consultancyviewdelete;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_consultancyclose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_consultancycreate;
    private javax.swing.JPanel jPanel_consultancyview;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_consultancyview;
    private javax.swing.JTextField jTextField_consultancycreateamount;
    private javax.swing.JTextField jTextField_consultancycreatedate;
    private javax.swing.JTextField jTextField_consultancycreatediscount;
    private javax.swing.JTextField jTextField_consultancycreatedoctorid;
    private javax.swing.JTextField jTextField_consultancycreatedoctorname;
    private javax.swing.JTextField jTextField_consultancycreateid;
    private javax.swing.JTextField jTextField_consultancycreatenetamount;
    private javax.swing.JTextField jTextField_consultancycreatepatientid;
    private javax.swing.JTextField jTextField_consultancycreatepatientname;
    private javax.swing.JTextField jTextField_consultancyviewenterkey;
    // End of variables declaration//GEN-END:variables

    private void loadTbl(){
        try{
            DefaultTableModel dtm = (DefaultTableModel)jTable_consultancyview.getModel();
            ResultSet rs = mc.getData("SELECT consultancy.id, patient.name, doctor.name, consultancy.amount, consultancy.discount, consultancy.net_amount, consultancy.date FROM consultancy, patient, doctor WHERE consultancy.patient = patient.id AND consultancy.doctor = doctor.id");
            while(rs.next()){
                Vector vtr = new Vector();
                vtr.add(rs.getString("consultancy.id"));
                vtr.add(rs.getString("consultancy.date"));
                vtr.add(rs.getString("patient.name"));
                vtr.add(rs.getString("doctor.name"));
                vtr.add(rs.getString("consultancy.amount"));
                vtr.add(rs.getString("consultancy.discount"));
                vtr.add(rs.getString("consultancy.net_amount"));
                dtm.addRow(vtr);
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
