/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.JPanel;

/**
 *
 * @author Samson
 */
public class HomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesGUI
     */
    int mousepX;
    int mousepY;
    boolean WindowOpen;
    
    public HomeGUI() {
        initComponents();
        
        WindowOpen = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_homeclose = new javax.swing.JLabel();
        jButton_homelogout = new javax.swing.JButton();
        jPanel_homepatient = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel_homedoctor = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel_homesupplier = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel_homemedicine = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel_hometest = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel_homeconsult = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel_homepurchase = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel_homesales = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_homelab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_homeaccounts = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_homereports = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel_homesetting = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(45, 120, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_homeclose.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel_homeclose.setForeground(new java.awt.Color(45, 120, 230));
        jLabel_homeclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_homeclose.setText("X");
        jLabel_homeclose.setAlignmentY(0.0F);
        jLabel_homeclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_homecloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_homeclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        jButton_homelogout.setBackground(new java.awt.Color(45, 120, 230));
        jButton_homelogout.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jButton_homelogout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_homelogout.setText("Logout");
        jButton_homelogout.setAlignmentY(0.0F);
        jButton_homelogout.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 2)));
        jButton_homelogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homelogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_homelogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 50, 150, 50));

        jPanel_homepatient.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homepatient.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homepatient.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homepatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homepatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homepatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homepatientMouseExited(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Sick_75px.png"))); // NOI18N

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("PATIENT");

        javax.swing.GroupLayout jPanel_homepatientLayout = new javax.swing.GroupLayout(jPanel_homepatient);
        jPanel_homepatient.setLayout(jPanel_homepatientLayout);
        jPanel_homepatientLayout.setHorizontalGroup(
            jPanel_homepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homepatientLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homepatientLayout.setVerticalGroup(
            jPanel_homepatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homepatientLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homepatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 216, 150, 148));

        jPanel_homedoctor.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homedoctor.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homedoctor.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homedoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homedoctorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homedoctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homedoctorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_homedoctorMousePressed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Doctor_Female_75px.png"))); // NOI18N

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("DOCTOR");

        javax.swing.GroupLayout jPanel_homedoctorLayout = new javax.swing.GroupLayout(jPanel_homedoctor);
        jPanel_homedoctor.setLayout(jPanel_homedoctorLayout);
        jPanel_homedoctorLayout.setHorizontalGroup(
            jPanel_homedoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homedoctorLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homedoctorLayout.setVerticalGroup(
            jPanel_homedoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homedoctorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homedoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 216, 150, 148));

        jPanel_homesupplier.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homesupplier.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homesupplier.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homesupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homesupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homesupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homesupplierMouseExited(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Supplier_75px.png"))); // NOI18N

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SUPPLIER");

        javax.swing.GroupLayout jPanel_homesupplierLayout = new javax.swing.GroupLayout(jPanel_homesupplier);
        jPanel_homesupplier.setLayout(jPanel_homesupplierLayout);
        jPanel_homesupplierLayout.setHorizontalGroup(
            jPanel_homesupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homesupplierLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homesupplierLayout.setVerticalGroup(
            jPanel_homesupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homesupplierLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homesupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 216, 150, 148));

        jPanel_homemedicine.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homemedicine.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homemedicine.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homemedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homemedicineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homemedicineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homemedicineMouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Medical_Bag_75px.png"))); // NOI18N

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MEDICINE");

        javax.swing.GroupLayout jPanel_homemedicineLayout = new javax.swing.GroupLayout(jPanel_homemedicine);
        jPanel_homemedicine.setLayout(jPanel_homemedicineLayout);
        jPanel_homemedicineLayout.setHorizontalGroup(
            jPanel_homemedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homemedicineLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homemedicineLayout.setVerticalGroup(
            jPanel_homemedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homemedicineLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homemedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 216, 150, 148));

        jPanel_hometest.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_hometest.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_hometest.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_hometest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_hometestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_hometestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_hometestMouseExited(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Test_Tube_75px.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("TEST");

        javax.swing.GroupLayout jPanel_hometestLayout = new javax.swing.GroupLayout(jPanel_hometest);
        jPanel_hometest.setLayout(jPanel_hometestLayout);
        jPanel_hometestLayout.setHorizontalGroup(
            jPanel_hometestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_hometestLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_hometestLayout.setVerticalGroup(
            jPanel_hometestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_hometestLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_hometest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 384, 150, 148));

        jPanel_homeconsult.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homeconsult.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homeconsult.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homeconsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homeconsultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homeconsultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homeconsultMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Stethoscope_75px.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CONSULT");

        javax.swing.GroupLayout jPanel_homeconsultLayout = new javax.swing.GroupLayout(jPanel_homeconsult);
        jPanel_homeconsult.setLayout(jPanel_homeconsultLayout);
        jPanel_homeconsultLayout.setHorizontalGroup(
            jPanel_homeconsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homeconsultLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homeconsultLayout.setVerticalGroup(
            jPanel_homeconsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeconsultLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homeconsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 384, 150, 148));

        jPanel_homepurchase.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homepurchase.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homepurchase.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homepurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homepurchaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homepurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homepurchaseMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Buy_75px.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PURCHASE");

        javax.swing.GroupLayout jPanel_homepurchaseLayout = new javax.swing.GroupLayout(jPanel_homepurchase);
        jPanel_homepurchase.setLayout(jPanel_homepurchaseLayout);
        jPanel_homepurchaseLayout.setHorizontalGroup(
            jPanel_homepurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homepurchaseLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homepurchaseLayout.setVerticalGroup(
            jPanel_homepurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homepurchaseLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homepurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 384, 150, 148));

        jPanel_homesales.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homesales.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homesales.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homesales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homesalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homesalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homesalesMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Checkout_75px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SALES");

        javax.swing.GroupLayout jPanel_homesalesLayout = new javax.swing.GroupLayout(jPanel_homesales);
        jPanel_homesales.setLayout(jPanel_homesalesLayout);
        jPanel_homesalesLayout.setHorizontalGroup(
            jPanel_homesalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homesalesLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homesalesLayout.setVerticalGroup(
            jPanel_homesalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homesalesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homesales, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 384, 150, 148));

        jPanel_homelab.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homelab.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homelab.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homelab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homelabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homelabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homelabMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Microscope_75px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LAB");

        javax.swing.GroupLayout jPanel_homelabLayout = new javax.swing.GroupLayout(jPanel_homelab);
        jPanel_homelab.setLayout(jPanel_homelabLayout);
        jPanel_homelabLayout.setHorizontalGroup(
            jPanel_homelabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homelabLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homelabLayout.setVerticalGroup(
            jPanel_homelabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homelabLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 552, 150, 148));

        jPanel_homeaccounts.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homeaccounts.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homeaccounts.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homeaccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homeaccountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homeaccountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homeaccountsMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Accounting_75px.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACCOUNTS");

        javax.swing.GroupLayout jPanel_homeaccountsLayout = new javax.swing.GroupLayout(jPanel_homeaccounts);
        jPanel_homeaccounts.setLayout(jPanel_homeaccountsLayout);
        jPanel_homeaccountsLayout.setHorizontalGroup(
            jPanel_homeaccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homeaccountsLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homeaccountsLayout.setVerticalGroup(
            jPanel_homeaccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homeaccountsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homeaccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 552, 150, 148));

        jPanel_homereports.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homereports.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homereports.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homereports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homereportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homereportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homereportsMouseExited(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Increase_75px.png"))); // NOI18N

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("REPORTS");

        javax.swing.GroupLayout jPanel_homereportsLayout = new javax.swing.GroupLayout(jPanel_homereports);
        jPanel_homereports.setLayout(jPanel_homereportsLayout);
        jPanel_homereportsLayout.setHorizontalGroup(
            jPanel_homereportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homereportsLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homereportsLayout.setVerticalGroup(
            jPanel_homereportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homereportsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homereports, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 552, 150, 148));

        jPanel_homesetting.setBackground(new java.awt.Color(110, 170, 230));
        jPanel_homesetting.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel_homesetting.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_homesetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_homesettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_homesettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_homesettingMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Services_75px.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SETTING");

        javax.swing.GroupLayout jPanel_homesettingLayout = new javax.swing.GroupLayout(jPanel_homesetting);
        jPanel_homesetting.setLayout(jPanel_homesettingLayout);
        jPanel_homesettingLayout.setHorizontalGroup(
            jPanel_homesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_homesettingLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_homesettingLayout.setVerticalGroup(
            jPanel_homesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_homesettingLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel_homesetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 552, 150, 148));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/Thayagam Poster 07.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LoginGUI login = new LoginGUI();
    PatientGUI patient = new PatientGUI();
    DoctorGUI doctor = new DoctorGUI();
    SupplierGUI supplier = new SupplierGUI();
    MedicineGUI medicine = new MedicineGUI();
    TestGUI test = new TestGUI();
    ConsultancyGUI consultancy = new ConsultancyGUI();
    PurchaseGUI purchase = new PurchaseGUI();
    SalesGUI sales = new SalesGUI();
    LabGUI lab = new LabGUI();
    AccountsGUI accounts = new AccountsGUI();
    ReportsGUI reports = new ReportsGUI();
    ReportsPurPopupGUI reportspopup = new ReportsPurPopupGUI();
    //SettingGUI setting = new SettingGUI();
    
    public void closeGUIs(){
        patient.setVisible(false);
        patient.dispose();
        doctor.setVisible(false);
        doctor.dispose();
        supplier.setVisible(false);
        supplier.dispose();
        medicine.setVisible(false);
        medicine.dispose();
        test.setVisible(false);
        test.dispose();
        consultancy.setVisible(false);
        consultancy.dispose();        
        purchase.setVisible(false);
        purchase.dispose();
        sales.setVisible(false);
        sales.dispose();        
        lab.setVisible(false);
        lab.dispose();        
        accounts.setVisible(false);
        accounts.dispose();
        reports.setVisible(false);
        reports.dispose();
        reportspopup.setVisible(false);
        reportspopup.dispose();        
        //setting.setVisible(false);
        //setting.dispose();        
    }
    
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel_homecloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_homecloseMouseClicked
        login.setVisible(true);
        closeGUIs();
        dispose();
    }//GEN-LAST:event_jLabel_homecloseMouseClicked

    private void jButton_homelogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homelogoutActionPerformed
        login.setVisible(true);
        closeGUIs();
        dispose();
    }//GEN-LAST:event_jButton_homelogoutActionPerformed

    private void jPanel_homepatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepatientMouseEntered
        setColor(jPanel_homepatient);
    }//GEN-LAST:event_jPanel_homepatientMouseEntered

    private void jPanel_homepatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepatientMouseExited
        resetColor(jPanel_homepatient);
    }//GEN-LAST:event_jPanel_homepatientMouseExited

    private void jPanel_homedoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homedoctorMouseEntered
        setColor(jPanel_homedoctor);
    }//GEN-LAST:event_jPanel_homedoctorMouseEntered

    private void jPanel_homedoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homedoctorMouseExited
        resetColor(jPanel_homedoctor);
    }//GEN-LAST:event_jPanel_homedoctorMouseExited

    private void jPanel_homedoctorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homedoctorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_homedoctorMousePressed

    private void jPanel_homepatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepatientMouseClicked
        if(WindowOpen == false){
            patient.setVisible(true);  
            patient.pack();
        }
        else{
            patient.toFront();
        }
    }//GEN-LAST:event_jPanel_homepatientMouseClicked

    private void jPanel_homesupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesupplierMouseEntered
        setColor(jPanel_homesupplier);
    }//GEN-LAST:event_jPanel_homesupplierMouseEntered

    private void jPanel_homesupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesupplierMouseExited
        resetColor(jPanel_homesupplier);
    }//GEN-LAST:event_jPanel_homesupplierMouseExited

    private void jPanel_homemedicineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homemedicineMouseEntered
        setColor(jPanel_homemedicine);
    }//GEN-LAST:event_jPanel_homemedicineMouseEntered

    private void jPanel_homemedicineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homemedicineMouseExited
        resetColor(jPanel_homemedicine);
    }//GEN-LAST:event_jPanel_homemedicineMouseExited

    private void jPanel_hometestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_hometestMouseEntered
        setColor(jPanel_hometest);
    }//GEN-LAST:event_jPanel_hometestMouseEntered

    private void jPanel_hometestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_hometestMouseExited
        resetColor(jPanel_hometest);
    }//GEN-LAST:event_jPanel_hometestMouseExited

    private void jPanel_homeconsultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeconsultMouseEntered
        setColor(jPanel_homeconsult);
    }//GEN-LAST:event_jPanel_homeconsultMouseEntered

    private void jPanel_homeconsultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeconsultMouseExited
        resetColor(jPanel_homeconsult);
    }//GEN-LAST:event_jPanel_homeconsultMouseExited

    private void jPanel_homepurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepurchaseMouseEntered
        setColor(jPanel_homepurchase);
    }//GEN-LAST:event_jPanel_homepurchaseMouseEntered

    private void jPanel_homepurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepurchaseMouseExited
        resetColor(jPanel_homepurchase);
    }//GEN-LAST:event_jPanel_homepurchaseMouseExited

    private void jPanel_homesalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesalesMouseEntered
        setColor(jPanel_homesales);
    }//GEN-LAST:event_jPanel_homesalesMouseEntered

    private void jPanel_homesalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesalesMouseExited
        resetColor(jPanel_homesales);
    }//GEN-LAST:event_jPanel_homesalesMouseExited

    private void jPanel_homelabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homelabMouseEntered
        setColor(jPanel_homelab);
    }//GEN-LAST:event_jPanel_homelabMouseEntered

    private void jPanel_homelabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homelabMouseExited
        resetColor(jPanel_homelab);
    }//GEN-LAST:event_jPanel_homelabMouseExited

    private void jPanel_homeaccountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeaccountsMouseEntered
        setColor(jPanel_homeaccounts);
    }//GEN-LAST:event_jPanel_homeaccountsMouseEntered

    private void jPanel_homeaccountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeaccountsMouseExited
        resetColor(jPanel_homeaccounts);
    }//GEN-LAST:event_jPanel_homeaccountsMouseExited

    private void jPanel_homereportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homereportsMouseEntered
        setColor(jPanel_homereports);
    }//GEN-LAST:event_jPanel_homereportsMouseEntered

    private void jPanel_homereportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homereportsMouseExited
        resetColor(jPanel_homereports);
    }//GEN-LAST:event_jPanel_homereportsMouseExited

    private void jPanel_homesettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesettingMouseEntered
        setColor(jPanel_homesetting);
    }//GEN-LAST:event_jPanel_homesettingMouseEntered

    private void jPanel_homesettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesettingMouseExited
        resetColor(jPanel_homesetting);
    }//GEN-LAST:event_jPanel_homesettingMouseExited

    private void jPanel_homedoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homedoctorMouseClicked
        if(WindowOpen == false){
            doctor.setVisible(true);  
        }
        else{
            doctor.toFront();
        }
    }//GEN-LAST:event_jPanel_homedoctorMouseClicked

    private void jPanel_homesupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesupplierMouseClicked
        if(WindowOpen == false){
            supplier.setVisible(true);  
        }
        else{
            supplier.toFront();
        }
    }//GEN-LAST:event_jPanel_homesupplierMouseClicked

    private void jPanel_homemedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homemedicineMouseClicked
        if(WindowOpen == false){
            medicine.setVisible(true);
            medicine.pack();
        }
        else{
            medicine.toFront();
            medicine.pack();
        }
    }//GEN-LAST:event_jPanel_homemedicineMouseClicked

    private void jPanel_hometestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_hometestMouseClicked
        if(WindowOpen == false){
            test.setVisible(true);  
        }
        else{
            test.toFront();
        }
    }//GEN-LAST:event_jPanel_hometestMouseClicked

    private void jPanel_homeconsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeconsultMouseClicked
        if(WindowOpen == false){
            consultancy.setVisible(true);  
        }
        else{
            consultancy.toFront();
        }
    }//GEN-LAST:event_jPanel_homeconsultMouseClicked

    private void jPanel_homepurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homepurchaseMouseClicked
        if(WindowOpen == false){
            purchase.setVisible(true);
            purchase.pack();
        }
        else{
            purchase.toFront();
            purchase.pack();
        }
    }//GEN-LAST:event_jPanel_homepurchaseMouseClicked

    private void jPanel_homesalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesalesMouseClicked
        if(WindowOpen == false){
            sales.setVisible(true);  
        }
        else{
            sales.toFront();
        }
    }//GEN-LAST:event_jPanel_homesalesMouseClicked

    private void jPanel_homelabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homelabMouseClicked
        if(WindowOpen == false){
            lab.setVisible(true);  
        }
        else{
            lab.toFront();
        }
    }//GEN-LAST:event_jPanel_homelabMouseClicked

    private void jPanel_homeaccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homeaccountsMouseClicked
        if(WindowOpen == false){
            accounts.setVisible(true);  
        }
        else{
            accounts.toFront();
        }
    }//GEN-LAST:event_jPanel_homeaccountsMouseClicked

    private void jPanel_homereportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homereportsMouseClicked
        if(WindowOpen == false){
            reports.setVisible(true);  
        }
        else{
            reports.toFront();
        }
    }//GEN-LAST:event_jPanel_homereportsMouseClicked

    private void jPanel_homesettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_homesettingMouseClicked
        /*if(WindowOpen == false){
            setting.setVisible(true);  
        }
        else{
            setting.toFront();
        }*/
    }//GEN-LAST:event_jPanel_homesettingMouseClicked

    public void setColor(JPanel Panel){
        Panel.setBackground(new java.awt.Color(45,120,230));
    }
    
    public void resetColor(JPanel Panel){
        Panel.setBackground(new java.awt.Color(110, 170, 230));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_homelogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_homeclose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_homeaccounts;
    private javax.swing.JPanel jPanel_homeconsult;
    private javax.swing.JPanel jPanel_homedoctor;
    private javax.swing.JPanel jPanel_homelab;
    private javax.swing.JPanel jPanel_homemedicine;
    private javax.swing.JPanel jPanel_homepatient;
    private javax.swing.JPanel jPanel_homepurchase;
    private javax.swing.JPanel jPanel_homereports;
    private javax.swing.JPanel jPanel_homesales;
    private javax.swing.JPanel jPanel_homesetting;
    private javax.swing.JPanel jPanel_homesupplier;
    private javax.swing.JPanel jPanel_hometest;
    // End of variables declaration//GEN-END:variables
}
