/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Samson
 */
public class MedicineGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesGUI
     */
    int mousepX;
    int mousepY;
    String sid, nxtsid, filename;
    String[] data = new String[9];
    
    public MedicineGUI() {
        initComponents();
        
        loadTbl();
        
        
        sid = "";
        nxtsid = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_medicineadd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_medicineaddid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_medicineaddname = new javax.swing.JTextField();
        jTextField_medicineaddpurchaseunit = new javax.swing.JTextField();
        jTextField_medicineaddsalesunit = new javax.swing.JTextField();
        jButton_medicineaddreset = new javax.swing.JButton();
        jButton_medicineaddsave = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_medicineadddes = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jTextField_medicineaddpurchaseprice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_medicineaddsalesprice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_medicineaddunitrelation = new javax.swing.JTextField();
        jDateChooser_medicineaddexp = new com.toedter.calendar.JDateChooser();
        jButton_medicineaddreset1 = new javax.swing.JButton();
        jPanel_medicineupdate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_medicineupdateid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField_medicineupdatename = new javax.swing.JTextField();
        jTextField_medicineupdatepurchaseunit = new javax.swing.JTextField();
        jTextField_medicineupdatesalesunit = new javax.swing.JTextField();
        jButton_medicineupdatereset = new javax.swing.JButton();
        jButton_medicineupdateupdate = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_medicineupdatedes = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jTextField_medicineupdatepurchaseprice = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField_medicineupdatesalesprice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_medicineupdateunitrelation = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_medicineupdateenterid = new javax.swing.JTextField();
        jButton_medicineupdatefetch = new javax.swing.JButton();
        jDateChooser_medicineupdateexp = new com.toedter.calendar.JDateChooser();
        jPanel_medicineview = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_medicineviewenterkey = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_medicineview = new javax.swing.JTable();
        jButton_medicineviewdelete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton_medicineviewdelete1 = new javax.swing.JButton();
        jPanel_medicineviewreload = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_medicineclose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 120, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(45, 120, 230));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("MEDICINE INFORMATION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 30, 360, -1));

        jTabbedPane1.setForeground(new java.awt.Color(50, 50, 50));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1180, 670));

        jPanel_medicineadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_medicineadd.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_medicineadd.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_medicineadd.setPreferredSize(new java.awt.Dimension(1180, 680));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Medicine ID");

        jTextField_medicineaddid.setEditable(false);
        jTextField_medicineaddid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddid.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_medicineaddid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Purchase unit");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Sales unit");

        jTextField_medicineaddname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddname.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jTextField_medicineaddpurchaseunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddpurchaseunit.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddpurchaseunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jTextField_medicineaddsalesunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddsalesunit.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddsalesunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton_medicineaddreset.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineaddreset.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineaddreset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineaddreset.setText("RESET");
        jButton_medicineaddreset.setAlignmentY(0.0F);
        jButton_medicineaddreset.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineaddreset.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineaddresetActionPerformed(evt);
            }
        });

        jButton_medicineaddsave.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineaddsave.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineaddsave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineaddsave.setText("SAVE");
        jButton_medicineaddsave.setAlignmentY(0.0F);
        jButton_medicineaddsave.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineaddsave.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddsave.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddsave.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineaddsaveActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel34.setText("Add New Medicine");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Exp date");

        jTextArea_medicineadddes.setColumns(20);
        jTextArea_medicineadddes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextArea_medicineadddes.setForeground(new java.awt.Color(50, 50, 50));
        jTextArea_medicineadddes.setRows(2);
        jTextArea_medicineadddes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jScrollPane1.setViewportView(jTextArea_medicineadddes);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel19.setText("Purchase price");

        jTextField_medicineaddpurchaseprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddpurchaseprice.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddpurchaseprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setText("Description");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setText("Sales price");

        jTextField_medicineaddsalesprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddsalesprice.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddsalesprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Unit relation");

        jTextField_medicineaddunitrelation.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineaddunitrelation.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineaddunitrelation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jDateChooser_medicineaddexp.setBackground(new java.awt.Color(250, 250, 250));
        jDateChooser_medicineaddexp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jDateChooser_medicineaddexp.setForeground(new java.awt.Color(50, 50, 50));
        jDateChooser_medicineaddexp.setDateFormatString("yyyy-MM-dd");
        jDateChooser_medicineaddexp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jDateChooser_medicineaddexp.setMaximumSize(new java.awt.Dimension(400, 27));
        jDateChooser_medicineaddexp.setMinSelectableDate(new java.util.Date(-62135785728000L));
        jDateChooser_medicineaddexp.setMinimumSize(new java.awt.Dimension(400, 27));
        jDateChooser_medicineaddexp.setPreferredSize(new java.awt.Dimension(400, 27));

        jButton_medicineaddreset1.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineaddreset1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineaddreset1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineaddreset1.setText("Import");
        jButton_medicineaddreset1.setAlignmentY(0.0F);
        jButton_medicineaddreset1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineaddreset1.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset1.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset1.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineaddreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineaddreset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_medicineaddLayout = new javax.swing.GroupLayout(jPanel_medicineadd);
        jPanel_medicineadd.setLayout(jPanel_medicineaddLayout);
        jPanel_medicineaddLayout.setHorizontalGroup(
            jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineaddLayout.createSequentialGroup()
                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_medicineaddexp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jTextField_medicineaddsalesunit)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel34)
                            .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_medicineaddname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_medicineaddid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_medicineaddpurchaseunit))))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_medicineaddunitrelation)
                                    .addComponent(jTextField_medicineaddsalesprice)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jTextField_medicineaddpurchaseprice, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jButton_medicineaddreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_medicineaddsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_medicineaddreset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel_medicineaddLayout.setVerticalGroup(
            jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineaddLayout.createSequentialGroup()
                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jButton_medicineaddreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_medicineaddid)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_medicineaddname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineaddpurchaseunit)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineaddpurchaseprice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_medicineaddsalesprice))
                            .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_medicineaddsalesunit)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_medicineaddunitrelation))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel_medicineaddLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser_medicineaddexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel_medicineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_medicineaddreset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_medicineaddsave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("ADD RECORD", jPanel_medicineadd);

        jPanel_medicineupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_medicineupdate.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_medicineupdate.setMinimumSize(new java.awt.Dimension(1180, 680));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Medicine ID");

        jTextField_medicineupdateid.setEditable(false);
        jTextField_medicineupdateid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdateid.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_medicineupdateid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Purchase unit");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setText("Sales unit");

        jTextField_medicineupdatename.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdatename.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdatename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jTextField_medicineupdatepurchaseunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdatepurchaseunit.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdatepurchaseunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jTextField_medicineupdatesalesunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdatesalesunit.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdatesalesunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton_medicineupdatereset.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineupdatereset.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineupdatereset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineupdatereset.setText("RESET");
        jButton_medicineupdatereset.setAlignmentY(0.0F);
        jButton_medicineupdatereset.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineupdatereset.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatereset.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatereset.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineupdateresetActionPerformed(evt);
            }
        });

        jButton_medicineupdateupdate.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineupdateupdate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineupdateupdate.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineupdateupdate.setText("UPDATE");
        jButton_medicineupdateupdate.setAlignmentY(0.0F);
        jButton_medicineupdateupdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineupdateupdate.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdateupdate.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdateupdate.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdateupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineupdateupdateActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel38.setText("Update Existing Medicine");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel24.setText("Exp date");

        jTextArea_medicineupdatedes.setColumns(20);
        jTextArea_medicineupdatedes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextArea_medicineupdatedes.setForeground(new java.awt.Color(50, 50, 50));
        jTextArea_medicineupdatedes.setRows(2);
        jTextArea_medicineupdatedes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jScrollPane3.setViewportView(jTextArea_medicineupdatedes);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel25.setText("Purchase price");

        jTextField_medicineupdatepurchaseprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdatepurchaseprice.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdatepurchaseprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setText("Description");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel27.setText("Sales price");

        jTextField_medicineupdatesalesprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdatesalesprice.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdatesalesprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel28.setText("Unit relation");

        jTextField_medicineupdateunitrelation.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdateunitrelation.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdateunitrelation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel29.setText("Enter ID");

        jTextField_medicineupdateenterid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineupdateenterid.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineupdateenterid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_medicineupdateenterid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_medicineupdateenteridMouseClicked(evt);
            }
        });

        jButton_medicineupdatefetch.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineupdatefetch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineupdatefetch.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineupdatefetch.setText("FETCH");
        jButton_medicineupdatefetch.setAlignmentY(0.0F);
        jButton_medicineupdatefetch.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineupdatefetch.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatefetch.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatefetch.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineupdatefetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineupdatefetchActionPerformed(evt);
            }
        });

        jDateChooser_medicineupdateexp.setBackground(new java.awt.Color(250, 250, 250));
        jDateChooser_medicineupdateexp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jDateChooser_medicineupdateexp.setForeground(new java.awt.Color(50, 50, 50));
        jDateChooser_medicineupdateexp.setDateFormatString("yyyy-MM-dd");
        jDateChooser_medicineupdateexp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jDateChooser_medicineupdateexp.setMaximumSize(new java.awt.Dimension(400, 27));
        jDateChooser_medicineupdateexp.setMinSelectableDate(new java.util.Date(-62135785728000L));
        jDateChooser_medicineupdateexp.setMinimumSize(new java.awt.Dimension(400, 27));
        jDateChooser_medicineupdateexp.setPreferredSize(new java.awt.Dimension(400, 27));

        javax.swing.GroupLayout jPanel_medicineupdateLayout = new javax.swing.GroupLayout(jPanel_medicineupdate);
        jPanel_medicineupdate.setLayout(jPanel_medicineupdateLayout);
        jPanel_medicineupdateLayout.setHorizontalGroup(
            jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineupdateLayout.createSequentialGroup()
                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_medicineupdateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_medicineupdatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser_medicineupdateexp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jTextField_medicineupdatesalesunit)))
                            .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel38)
                                    .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField_medicineupdatename, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                            .addComponent(jTextField_medicineupdateid, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_medicineupdatepurchaseunit))))
                                .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addGap(75, 75, 75)
                                    .addComponent(jTextField_medicineupdateenterid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_medicineupdatefetch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_medicineupdateunitrelation)
                                .addComponent(jTextField_medicineupdatesalesprice)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jTextField_medicineupdatepurchaseprice, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(50, 50, 50))
        );
        jPanel_medicineupdateLayout.setVerticalGroup(
            jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineupdateLayout.createSequentialGroup()
                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel38)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextField_medicineupdateenterid)
                            .addComponent(jButton_medicineupdatefetch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_medicineupdateid)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField_medicineupdatename)))
                            .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineupdatepurchaseunit)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineupdatepurchaseprice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineupdatesalesunit)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineupdatesalesprice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_medicineupdateunitrelation)))
                    .addGroup(jPanel_medicineupdateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser_medicineupdateexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel_medicineupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_medicineupdatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_medicineupdateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("UPDATE RECORD", jPanel_medicineupdate);

        jPanel_medicineview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_medicineview.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_medicineview.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_medicineview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_medicineviewMouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel31.setText("Enter keyword");

        jTextField_medicineviewenterkey.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_medicineviewenterkey.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_medicineviewenterkey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_medicineviewenterkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_medicineviewenterkeyKeyReleased(evt);
            }
        });

        jTable_medicineview.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable_medicineview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "DESCRIPTION", "PUR UNIT", "PUR PRICE", "SAL UNIT", "SAL PRICE", "EXP DATE", "RATIO", "QTY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_medicineview.setSelectionBackground(new java.awt.Color(45, 120, 230));
        jScrollPane2.setViewportView(jTable_medicineview);
        if (jTable_medicineview.getColumnModel().getColumnCount() > 0) {
            jTable_medicineview.getColumnModel().getColumn(0).setMinWidth(100);
            jTable_medicineview.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable_medicineview.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable_medicineview.getColumnModel().getColumn(3).setMinWidth(100);
            jTable_medicineview.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_medicineview.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable_medicineview.getColumnModel().getColumn(4).setMinWidth(80);
            jTable_medicineview.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable_medicineview.getColumnModel().getColumn(4).setMaxWidth(80);
            jTable_medicineview.getColumnModel().getColumn(5).setMinWidth(100);
            jTable_medicineview.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable_medicineview.getColumnModel().getColumn(5).setMaxWidth(100);
            jTable_medicineview.getColumnModel().getColumn(6).setMinWidth(80);
            jTable_medicineview.getColumnModel().getColumn(6).setPreferredWidth(80);
            jTable_medicineview.getColumnModel().getColumn(6).setMaxWidth(80);
            jTable_medicineview.getColumnModel().getColumn(7).setMinWidth(100);
            jTable_medicineview.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable_medicineview.getColumnModel().getColumn(7).setMaxWidth(100);
            jTable_medicineview.getColumnModel().getColumn(8).setMinWidth(80);
            jTable_medicineview.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTable_medicineview.getColumnModel().getColumn(8).setMaxWidth(80);
            jTable_medicineview.getColumnModel().getColumn(9).setMinWidth(80);
            jTable_medicineview.getColumnModel().getColumn(9).setPreferredWidth(80);
            jTable_medicineview.getColumnModel().getColumn(9).setMaxWidth(80);
        }

        jButton_medicineviewdelete.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineviewdelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineviewdelete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineviewdelete.setText("DELETE");
        jButton_medicineviewdelete.setAlignmentY(0.0F);
        jButton_medicineviewdelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineviewdelete.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineviewdeleteActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel18.setText("View Medicine");

        jButton_medicineviewdelete1.setBackground(new java.awt.Color(45, 120, 230));
        jButton_medicineviewdelete1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_medicineviewdelete1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_medicineviewdelete1.setText("Export");
        jButton_medicineviewdelete1.setAlignmentY(0.0F);
        jButton_medicineviewdelete1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_medicineviewdelete1.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete1.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete1.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_medicineviewdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicineviewdelete1ActionPerformed(evt);
            }
        });

        jPanel_medicineviewreload.setToolTipText("Reload this page");
        jPanel_medicineviewreload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_medicineviewreloadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_medicineviewreloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_medicineviewreloadMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Image/icons8_Reset_25px.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel_medicineviewreloadLayout = new javax.swing.GroupLayout(jPanel_medicineviewreload);
        jPanel_medicineviewreload.setLayout(jPanel_medicineviewreloadLayout);
        jPanel_medicineviewreloadLayout.setHorizontalGroup(
            jPanel_medicineviewreloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
        jPanel_medicineviewreloadLayout.setVerticalGroup(
            jPanel_medicineviewreloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineviewreloadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel_medicineviewLayout = new javax.swing.GroupLayout(jPanel_medicineview);
        jPanel_medicineview.setLayout(jPanel_medicineviewLayout);
        jPanel_medicineviewLayout.setHorizontalGroup(
            jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_medicineviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel_medicineviewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_medicineviewLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(75, 75, 75)
                        .addComponent(jTextField_medicineviewenterkey, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_medicineviewLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 784, Short.MAX_VALUE)
                        .addComponent(jButton_medicineviewdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineviewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineviewLayout.createSequentialGroup()
                        .addComponent(jButton_medicineviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineviewLayout.createSequentialGroup()
                        .addComponent(jPanel_medicineviewreload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel_medicineviewLayout.setVerticalGroup(
            jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_medicineviewLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel_medicineviewreload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jButton_medicineviewdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel_medicineviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_medicineviewenterkey)
                    .addComponent(jButton_medicineviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VIEW RECORD", jPanel_medicineview);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1180, 670));

        jLabel_medicineclose.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel_medicineclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_medicineclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_medicineclose.setText("X");
        jLabel_medicineclose.setAlignmentY(0.0F);
        jLabel_medicineclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_medicinecloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_medicineclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    MysqlConnection mc = new MysqlConnection();
    
    public void genId(){
        //ME000000
        try{
            ResultSet rs = mc.getData("SELECT id FROM medicine ORDER BY id DESC LIMIT 1");
		if(rs.next()){
			String idval = rs.getString("id");
			int ln = idval.length();
			String stxt = idval.substring(0, 2);
			String snum = idval.substring(2, ln);
                        String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
			sid = stxt + num;
		}
		else{
			sid = "ME000001";
		}
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }
    
    public void setId(){
        int ln = sid.length();
        String stxt = sid.substring(0, 2);
	String snum = sid.substring(2, ln);
	String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
	nxtsid = stxt + num;
    }    
    
    public void excelExport(){
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("Medicines Detail");
        try{
            ResultSet rs = mc.getData("SELECT id, name, description, purchase_unit, purchase_price, sales_unit, sales_price, exp_date, unit_relation, quantity FROM medicine");
            Map<String, Object[]> data = new TreeMap<String, Object[]>();
            data.put("1", new Object[]{"ID", "NAME", "DESCRIPTION", "PURCHASED UNIT", "PURCHASE PRICE", "SALES UNIT", "SALES PRICE", "EXPIRE DATE", "UNIT RELATION", "QUANTITY"});
            String srow = "2";
            while(rs.next()){
                data.put(srow, new Object[]{rs.getString("id"), rs.getString("name"), rs.getString("description"), rs.getString("purchase_unit"), rs.getString("purchase_price"), rs.getString("sales_unit"), rs.getString("sales_price"), rs.getString("exp_date"), rs.getString("unit_relation"), rs.getString("quantity")});
                srow += "1";
            }
            Set<String> keyset = data.keySet();
            int rownum = 0;
            for(String key : keyset){
                Row row = sheet.createRow(rownum++);
                Object[] objArr = data.get(key);
                int cellnum = 0;
                for(Object obj : objArr){
                    Cell cell = row.createCell(cellnum++);
                    if(obj instanceof String){
                        cell.setCellValue((String)obj);
                    }
                    else if(obj instanceof Integer){
                        cell.setCellValue((Integer)obj);
                    }
                }
            }
            FileOutputStream out = new FileOutputStream(new File("C:\\Users\\Chathushka\\Desktop\\medicines_detail.xlsx"));
            workbook.write(out);
            out.close();
            JOptionPane.showMessageDialog(null, "The file \"medicines_detail.xlsx\" exported to desktop successfully!");
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }    
    
    public void excelImport(String filename){
        this.filename = filename;
        try{
            FileInputStream file = new FileInputStream(new File(this.filename));
            XSSFWorkbook workbook = new XSSFWorkbook(file);
            XSSFSheet sheet = workbook.getSheetAt(0);
            
            Iterator<Row> rowIterator = sheet.rowIterator();
            while(rowIterator.hasNext()){
                Row row = rowIterator.next();
                genId();
                Iterator<Cell> cellIterator = row.cellIterator();
                int i = 0;
                while(cellIterator.hasNext()){
                    Cell cell = cellIterator.next();
                    if(cell.getCellTypeEnum() == CellType.STRING){
                        data[i] = cell.getStringCellValue();
                        i++;
                    }
                }
                mc.putData("INSERT INTO medicine (id, name, description, purchase_unit, purchase_price, sales_unit, sales_price, exp_date, unit_relation, quantity) VALUES ('"+sid+"', '"+data[0]+"', '"+data[1]+"', '"+data[2]+"', '"+data[3]+"', '"+data[4]+"', '"+data[5]+"', '"+data[6]+"', '"+data[7]+"', '"+data[8]+"')");
            }
            file.close();
            JOptionPane.showMessageDialog(null, "The data imported successfully!");
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }

    public void setColor(JPanel Panel){
        Panel.setBackground(new java.awt.Color(200,200,200));
    }
    
    public void resetColor(JPanel Panel){
        Panel.setBackground(new java.awt.Color(220,220,220));
    }    
    
    private void jLabel_medicinecloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_medicinecloseMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jLabel_medicinecloseMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButton_medicineaddsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineaddsaveActionPerformed
        if(jTextField_medicineaddname.getText().isEmpty() || jTextArea_medicineadddes.getText().isEmpty() || jTextField_medicineaddpurchaseunit.getText().isEmpty() || jTextField_medicineaddpurchaseprice.getText().isEmpty() || jTextField_medicineaddsalesunit.getText().isEmpty() || jTextField_medicineaddsalesprice.getText().isEmpty() || ((JTextField)jDateChooser_medicineaddexp.getDateEditor().getUiComponent()).getText().isEmpty() || jTextField_medicineaddunitrelation.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
        else{
            try{
                genId();
                setId();
                mc.putData("INSERT INTO medicine (id, name, description, purchase_unit, purchase_price, sales_unit, sales_price, exp_date, unit_relation, quantity) VALUES ('"+sid+"', '"+jTextField_medicineaddname.getText()+"', '"+jTextArea_medicineadddes.getText()+"', '"+jTextField_medicineaddpurchaseunit.getText()+"', '"+jTextField_medicineaddpurchaseprice.getText()+"', '"+jTextField_medicineaddsalesunit.getText()+"', '"+jTextField_medicineaddsalesprice.getText()+"', '"+((JTextField)jDateChooser_medicineaddexp.getDateEditor().getUiComponent()).getText()+"', '"+jTextField_medicineaddunitrelation.getText()+"', '"+0.00+"')");
                jTextField_medicineaddid.setText(nxtsid);
                jTextField_medicineaddname.setText(null);
                jTextArea_medicineadddes.setText(null);
                jTextField_medicineaddpurchaseunit.setText(null);
                jTextField_medicineaddpurchaseprice.setText(null);
                jTextField_medicineaddsalesunit.setText(null);
                jTextField_medicineaddsalesprice.setText(null);
                ((JTextField)jDateChooser_medicineaddexp.getDateEditor().getUiComponent()).setText(null);
                jTextField_medicineaddunitrelation.setText(null);
            JOptionPane.showMessageDialog(null, "Data added");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        dtm.setRowCount(0);
        loadTbl();
    }//GEN-LAST:event_jButton_medicineaddsaveActionPerformed

    private void jButton_medicineaddresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineaddresetActionPerformed
        jTextField_medicineaddname.setText(null);
        jTextArea_medicineadddes.setText(null);
        jTextField_medicineaddpurchaseunit.setText(null);
        jTextField_medicineaddpurchaseprice.setText(null);
        jTextField_medicineaddsalesunit.setText(null);
        jTextField_medicineaddsalesprice.setText(null);
        ((JTextField)jDateChooser_medicineaddexp.getDateEditor().getUiComponent()).setText(null);
        jTextField_medicineaddunitrelation.setText(null);
    }//GEN-LAST:event_jButton_medicineaddresetActionPerformed

    private void jTextField_medicineupdateenteridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_medicineupdateenteridMouseClicked
        jTextField_medicineupdateid.setText(null);
        jTextField_medicineupdatename.setText(null);
        jTextArea_medicineupdatedes.setText(null);
        jTextField_medicineupdatepurchaseunit.setText(null);
        jTextField_medicineupdatepurchaseprice.setText(null);
        jTextField_medicineupdatesalesunit.setText(null);
        jTextField_medicineupdatesalesprice.setText(null);
        ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).setText(null);
        jTextField_medicineupdateunitrelation.setText(null);
    }//GEN-LAST:event_jTextField_medicineupdateenteridMouseClicked

    private void jButton_medicineupdatefetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineupdatefetchActionPerformed
        try{
            ResultSet rs = mc.getData("SELECT * FROM medicine WHERE id = '"+jTextField_medicineupdateenterid.getText()+"'");
            if(rs.first()){
                jTextField_medicineupdateid.setText(rs.getString("id"));
                jTextField_medicineupdatename.setText(rs.getString("name"));
                jTextArea_medicineupdatedes.setText(rs.getString("description"));
                jTextField_medicineupdatepurchaseunit.setText(rs.getString("purchase_unit"));
                jTextField_medicineupdatepurchaseprice.setText(rs.getString("purchase_price"));
                jTextField_medicineupdatesalesunit.setText(rs.getString("sales_unit"));
                jTextField_medicineupdatesalesprice.setText(rs.getString("sales_price"));
                ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).setText(rs.getString("exp_date"));
                jTextField_medicineupdateunitrelation.setText(rs.getString("unit_relation"));
            }
            else{
                JOptionPane.showMessageDialog(null, "No data found. Please try another!");
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }//GEN-LAST:event_jButton_medicineupdatefetchActionPerformed

    private void jButton_medicineupdateupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineupdateupdateActionPerformed
        if(jTextField_medicineupdateid.getText().isEmpty() || jTextField_medicineupdatename.getText().isEmpty() || jTextArea_medicineupdatedes.getText().isEmpty() || jTextField_medicineupdatepurchaseunit.getText().isEmpty() || jTextField_medicineupdatepurchaseprice.getText().isEmpty() || jTextField_medicineupdatesalesunit.getText().isEmpty() || jTextField_medicineupdatesalesprice.getText().isEmpty() || ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).getText().isEmpty() || jTextField_medicineupdateunitrelation.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
        else{
            String purmedi;
            String salmedi;
            String upmedi = jTextField_medicineupdateid.getText();
            try{
                Statement stmt = MysqlConnection.conn().createStatement();
                ResultSet rspi = stmt.executeQuery("SELECT purchase_item.medicine FROM purchase_item WHERE medicine = '"+upmedi+"'");
                if(rspi.first()){
                    purmedi = rspi.getString("purchase_item.medicine");
                }
                else{
                    purmedi = "";
                }
                ResultSet rssi = stmt.executeQuery("SELECT sales_item.medicine FROM sales_item WHERE medicine = '"+upmedi+"'");
                if(rssi.first()){
                    salmedi = rssi.getString("sales_item.medicine");
                }
                else{
                    salmedi = "";
                }
                if(purmedi.isEmpty() && salmedi.isEmpty()){
                    stmt.executeUpdate("UPDATE medicine SET name = '"+jTextField_medicineupdatename.getText()+"', description = '"+jTextArea_medicineupdatedes.getText()+"', purchase_unit = '"+jTextField_medicineupdatepurchaseunit.getText()+"', purchase_price = '"+jTextField_medicineupdatepurchaseprice.getText()+"', sales_unit = '"+jTextField_medicineupdatesalesunit.getText()+"', sales_price = '"+jTextField_medicineupdatesalesprice.getText()+"', exp_date = '"+((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).getText()+"', unit_relation = '"+jTextField_medicineupdateunitrelation.getText()+"', quantity = '"+0.00+"' WHERE id = '"+jTextField_medicineupdateid.getText()+"'");
                    JOptionPane.showMessageDialog(null, "Data Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Sorry, cannot update this data!");
                }
                jTextField_medicineupdateenterid.setText(null);
                jTextField_medicineupdateid.setText(null);
                jTextField_medicineupdatename.setText(null);
                jTextArea_medicineupdatedes.setText(null);
                jTextField_medicineupdatepurchaseunit.setText(null);
                jTextField_medicineupdatepurchaseprice.setText(null);
                jTextField_medicineupdatesalesunit.setText(null);
                jTextField_medicineupdatesalesprice.setText(null);
                ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).setText(null);
                jTextField_medicineupdateunitrelation.setText(null);                
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        dtm.setRowCount(0);
        loadTbl();
    }//GEN-LAST:event_jButton_medicineupdateupdateActionPerformed

    private void jButton_medicineupdateresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineupdateresetActionPerformed
        jTextField_medicineupdateenterid.setText(null);
        jTextField_medicineupdateid.setText(null);
        jTextField_medicineupdatename.setText(null);
        jTextArea_medicineupdatedes.setText(null);
        jTextField_medicineupdatepurchaseunit.setText(null);
        jTextField_medicineupdatepurchaseprice.setText(null);
        jTextField_medicineupdatesalesunit.setText(null);
        jTextField_medicineupdatesalesprice.setText(null);
        ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).setText(null);
        jTextField_medicineupdateunitrelation.setText(null);
    }//GEN-LAST:event_jButton_medicineupdateresetActionPerformed

    private void jTextField_medicineviewenterkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_medicineviewenterkeyKeyReleased
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        String search = jTextField_medicineviewenterkey.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(dtm);
        jTable_medicineview.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField_medicineviewenterkeyKeyReleased

    private void jButton_medicineviewdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineviewdeleteActionPerformed
        /*
        try{
            Statement stmt = MysqlConnection.conn().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT medicine FROM purchase_item WHERE medicine = '"+sri_id[i]+"'");
        
        ResultSet rs = mc.getData("SELECT * FROM medicine WHERE id = '"+jTextField_medicineupdateenterid.getText()+"'");
            if(rs.first()){
                jTextField_medicineupdateid.setText(rs.getString("id"));
                jTextField_medicineupdatename.setText(rs.getString("name"));
                jTextArea_medicineupdatedes.setText(rs.getString("description"));
                jTextField_medicineupdatepurchaseunit.setText(rs.getString("purchase_unit"));
                jTextField_medicineupdatepurchaseprice.setText(rs.getString("purchase_price"));
                jTextField_medicineupdatesalesunit.setText(rs.getString("sales_unit"));
                jTextField_medicineupdatesalesprice.setText(rs.getString("sales_price"));
                ((JTextField)jDateChooser_medicineupdateexp.getDateEditor().getUiComponent()).setText(rs.getString("exp_date"));
                jTextField_medicineupdateunitrelation.setText(rs.getString("unit_relation"));
            }
            else{
                JOptionPane.showMessageDialog(null, "No data found. Please try another!");
            }
        
            Statement stmt = MysqlConnection.conn().createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            return rs;  
        }
        */
        
        
        int sri[] = jTable_medicineview.getSelectedRows();
        String sri_id[] = new String[sri.length];
        String purmedi[] = new String[sri.length];
        String salmedi[] = new String[sri.length];
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        if(sri.length > 0){
            try{
                for(int i = sri.length - 1; i >= 0; i--){
                    sri_id[i] = jTable_medicineview.getModel().getValueAt(sri[i], 0).toString();
                    Statement stmt = MysqlConnection.conn().createStatement();
                    ResultSet rspi = stmt.executeQuery("SELECT purchase_item.medicine FROM purchase_item WHERE medicine = '"+sri_id[i]+"'");
                    if(rspi.first()){
                        purmedi[i] = rspi.getString("purchase_item.medicine");
                    }
                    else{
                        purmedi[i] = "";
                    }
                    ResultSet rssi = stmt.executeQuery("SELECT sales_item.medicine FROM sales_item WHERE medicine = '"+sri_id[i]+"'");
                    if(rssi.first()){
                        salmedi[i] = rssi.getString("sales_item.medicine");
                    }
                    else{
                        salmedi[i] = "";
                    }
                    if(purmedi[i].isEmpty() && salmedi[i].isEmpty()){
                        stmt.executeUpdate("DELETE FROM medicine WHERE id = '"+sri_id[i]+"'");
                        dtm.removeRow(sri[i]);
                        JOptionPane.showMessageDialog(null, "Data deleted successfully!");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Sorry, cannot delete this data!");
                    }
                }
                dtm.setRowCount(0);
                loadTbl();
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to delete data!");
        }
        
        /*
        int sri[] = jTable_medicineview.getSelectedRows();
        String sri_id[] = new String[sri.length];
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        if(sri.length > 0){
            try{
                for(int i = sri.length - 1; i >= 0; i--){
                    sri_id[i] = jTable_medicineview.getModel().getValueAt(sri[i], 0).toString();
                    Statement stmt = MysqlConnection.conn().createStatement();
                    stmt.executeUpdate("DELETE FROM medicine WHERE id = '"+sri_id[i]+"'");
                    dtm.removeRow(sri[i]);
                }
                dtm.setRowCount(0);
                loadTbl();
                JOptionPane.showMessageDialog(null, "Data deleted successfully!");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to delete data!");
        }        
        */
    }//GEN-LAST:event_jButton_medicineviewdeleteActionPerformed

    private void jPanel_medicineviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_medicineviewMouseClicked
        jTable_medicineview.clearSelection();
    }//GEN-LAST:event_jPanel_medicineviewMouseClicked

    private void jButton_medicineaddreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineaddreset1ActionPerformed
        FileFilter filter = new FileNameExtensionFilter("MS Office Documents", "xlsx");
        JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(filter);
        int returnval = chooser.showOpenDialog(null);
        if(returnval == JFileChooser.APPROVE_OPTION){
            File file = chooser.getSelectedFile();
            String fname = file.getAbsolutePath();
            excelImport(fname);
            DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
            dtm.setRowCount(0);
            loadTbl();            
        }
    }//GEN-LAST:event_jButton_medicineaddreset1ActionPerformed

    private void jButton_medicineviewdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicineviewdelete1ActionPerformed
        excelExport();
    }//GEN-LAST:event_jButton_medicineviewdelete1ActionPerformed

    private void jPanel_medicineviewreloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_medicineviewreloadMouseEntered
        setColor(jPanel_medicineviewreload);
    }//GEN-LAST:event_jPanel_medicineviewreloadMouseEntered

    private void jPanel_medicineviewreloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_medicineviewreloadMouseExited
        resetColor(jPanel_medicineviewreload);
    }//GEN-LAST:event_jPanel_medicineviewreloadMouseExited

    private void jPanel_medicineviewreloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_medicineviewreloadMouseClicked
        DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
        dtm.setRowCount(0);
        loadTbl();
    }//GEN-LAST:event_jPanel_medicineviewreloadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_medicineaddreset;
    private javax.swing.JButton jButton_medicineaddreset1;
    private javax.swing.JButton jButton_medicineaddsave;
    private javax.swing.JButton jButton_medicineupdatefetch;
    private javax.swing.JButton jButton_medicineupdatereset;
    private javax.swing.JButton jButton_medicineupdateupdate;
    private javax.swing.JButton jButton_medicineviewdelete;
    private javax.swing.JButton jButton_medicineviewdelete1;
    private com.toedter.calendar.JDateChooser jDateChooser_medicineaddexp;
    private com.toedter.calendar.JDateChooser jDateChooser_medicineupdateexp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_medicineclose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_medicineadd;
    private javax.swing.JPanel jPanel_medicineupdate;
    private javax.swing.JPanel jPanel_medicineview;
    private javax.swing.JPanel jPanel_medicineviewreload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable_medicineview;
    private javax.swing.JTextArea jTextArea_medicineadddes;
    private javax.swing.JTextArea jTextArea_medicineupdatedes;
    private javax.swing.JTextField jTextField_medicineaddid;
    private javax.swing.JTextField jTextField_medicineaddname;
    private javax.swing.JTextField jTextField_medicineaddpurchaseprice;
    private javax.swing.JTextField jTextField_medicineaddpurchaseunit;
    private javax.swing.JTextField jTextField_medicineaddsalesprice;
    private javax.swing.JTextField jTextField_medicineaddsalesunit;
    private javax.swing.JTextField jTextField_medicineaddunitrelation;
    private javax.swing.JTextField jTextField_medicineupdateenterid;
    private javax.swing.JTextField jTextField_medicineupdateid;
    private javax.swing.JTextField jTextField_medicineupdatename;
    private javax.swing.JTextField jTextField_medicineupdatepurchaseprice;
    private javax.swing.JTextField jTextField_medicineupdatepurchaseunit;
    private javax.swing.JTextField jTextField_medicineupdatesalesprice;
    private javax.swing.JTextField jTextField_medicineupdatesalesunit;
    private javax.swing.JTextField jTextField_medicineupdateunitrelation;
    private javax.swing.JTextField jTextField_medicineviewenterkey;
    // End of variables declaration//GEN-END:variables

    public void loadTbl(){
        try{
            DefaultTableModel dtm = (DefaultTableModel)jTable_medicineview.getModel();
            ResultSet rs = mc.getData("SELECT id, name, description, purchase_unit, purchase_price, sales_unit, sales_price, exp_date, unit_relation, quantity FROM medicine");
            while(rs.next()){
                Vector vtr = new Vector();
                vtr.add(rs.getString("id"));
                vtr.add(rs.getString("name"));
                vtr.add(rs.getString("description"));
                vtr.add(rs.getString("purchase_unit"));
                vtr.add(rs.getString("purchase_price"));
                vtr.add(rs.getString("sales_unit"));
                vtr.add(rs.getString("sales_price"));
                vtr.add(rs.getString("exp_date"));
                vtr.add(rs.getString("unit_relation"));
                vtr.add(rs.getString("quantity"));
                dtm.addRow(vtr);
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
