/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import static java.lang.Thread.sleep;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samson
 */
public class SalesGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesGUI
     */
    int mousepX;
    int mousepY;
    int trc;
    int sri[], tri[];
    double salmediqty, stmediqty;
    String sid, sitmid, nxtsid, salmediid;
    String crg[];
    BigDecimal salesprice, mediqty, mediprice, price, discount, amount, totalamount, totaldiscount, netamount, bdprz, bddis;
    
    public SalesGUI() {
        
        sid = "";
        sitmid = "";
        nxtsid = "";
        salmediid = "";
        salmediqty = 0.00;
        stmediqty = 0.00;
        amount = new BigDecimal("0");
        
        initComponents();
        
        currentDate();
        genSalesItemId();
        loadTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_salescreate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_salescreateid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_salescreatepatientid = new javax.swing.JTextField();
        jTextField_salescreatemedicineid = new javax.swing.JTextField();
        jTextField_salescreatesalesunit = new javax.swing.JTextField();
        jTextField_salescreateprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_salescreatesalesprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_salescreatequantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_salescreatedate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_salescreatepatientname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_salescreatemedicinename = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_salescreatediscount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_salescreateamount = new javax.swing.JTextField();
        jButton_salescreatedelete = new javax.swing.JButton();
        jButton_salescreateupdate = new javax.swing.JButton();
        jButton_salescreatereset = new javax.swing.JButton();
        jButton_salescreateadd = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField_salescreatenetamount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_salescreatetotaldiscount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_salescreatetotalamount = new javax.swing.JTextField();
        jButton_salescreatecancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_salescreate = new javax.swing.JTable();
        jButton_salescreateprint = new javax.swing.JButton();
        jButton_salescreatesave = new javax.swing.JButton();
        jTextField_salescreatestock = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel_salesview = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_salesviewenterkey = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_salesview = new javax.swing.JTable();
        jButton_salesviewdelete = new javax.swing.JButton();
        jLabel_salesclose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(45, 120, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(45, 120, 230));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SALES INFORMATION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 30, 300, -1));

        jTabbedPane1.setForeground(new java.awt.Color(50, 50, 50));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1180, 670));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1180, 670));

        jPanel_salescreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_salescreate.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_salescreate.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_salescreate.setPreferredSize(new java.awt.Dimension(1180, 680));
        jPanel_salescreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_salescreateMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Sales ID");

        jTextField_salescreateid.setEditable(false);
        jTextField_salescreateid.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreateid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreateid.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreateid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Medicine ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Sales unit");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Price");

        jTextField_salescreatepatientid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatepatientid.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salescreatepatientid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salescreatepatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_salescreatepatientidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salescreatepatientidKeyReleased(evt);
            }
        });

        jTextField_salescreatemedicineid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatemedicineid.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salescreatemedicineid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salescreatemedicineid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_salescreatemedicineidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salescreatemedicineidKeyReleased(evt);
            }
        });

        jTextField_salescreatesalesunit.setEditable(false);
        jTextField_salescreatesalesunit.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatesalesunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatesalesunit.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreatesalesunit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jTextField_salescreateprice.setEditable(false);
        jTextField_salescreateprice.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreateprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreateprice.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreateprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Sales price");

        jTextField_salescreatesalesprice.setEditable(false);
        jTextField_salescreatesalesprice.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatesalesprice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatesalesprice.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreatesalesprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Qty");

        jTextField_salescreatequantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatequantity.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salescreatequantity.setText("0.00");
        jTextField_salescreatequantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salescreatequantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salescreatequantityKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Date");

        jTextField_salescreatedate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatedate.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salescreatedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Patient name");

        jTextField_salescreatepatientname.setEditable(false);
        jTextField_salescreatepatientname.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatepatientname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatepatientname.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreatepatientname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Medicine name");

        jTextField_salescreatemedicinename.setEditable(false);
        jTextField_salescreatemedicinename.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatemedicinename.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatemedicinename.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreatemedicinename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Discount");

        jTextField_salescreatediscount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatediscount.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salescreatediscount.setText("0.00");
        jTextField_salescreatediscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salescreatediscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salescreatediscountKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Amount");

        jTextField_salescreateamount.setEditable(false);
        jTextField_salescreateamount.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreateamount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreateamount.setForeground(new java.awt.Color(0, 0, 255));
        jTextField_salescreateamount.setText("0.00");
        jTextField_salescreateamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton_salescreatedelete.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreatedelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreatedelete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreatedelete.setText("DELETE");
        jButton_salescreatedelete.setAlignmentY(0.0F);
        jButton_salescreatedelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreatedelete.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_salescreatedelete.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_salescreatedelete.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_salescreatedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreatedeleteActionPerformed(evt);
            }
        });

        jButton_salescreateupdate.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreateupdate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreateupdate.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreateupdate.setText("UPDATE");
        jButton_salescreateupdate.setAlignmentY(0.0F);
        jButton_salescreateupdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreateupdate.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_salescreateupdate.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_salescreateupdate.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_salescreateupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreateupdateActionPerformed(evt);
            }
        });

        jButton_salescreatereset.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreatereset.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreatereset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreatereset.setText("RESET");
        jButton_salescreatereset.setAlignmentY(0.0F);
        jButton_salescreatereset.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreatereset.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_salescreatereset.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_salescreatereset.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_salescreatereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreateresetActionPerformed(evt);
            }
        });

        jButton_salescreateadd.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreateadd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreateadd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreateadd.setText("ADD");
        jButton_salescreateadd.setAlignmentY(0.0F);
        jButton_salescreateadd.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreateadd.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_salescreateadd.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_salescreateadd.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_salescreateadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreateaddActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("Net amount");

        jTextField_salescreatenetamount.setEditable(false);
        jTextField_salescreatenetamount.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatenetamount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatenetamount.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_salescreatenetamount.setText("0.00");
        jTextField_salescreatenetamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setText("Total discount");

        jTextField_salescreatetotaldiscount.setEditable(false);
        jTextField_salescreatetotaldiscount.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatetotaldiscount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatetotaldiscount.setForeground(new java.awt.Color(0, 150, 0));
        jTextField_salescreatetotaldiscount.setText("0.00");
        jTextField_salescreatetotaldiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("Total amount");

        jTextField_salescreatetotalamount.setEditable(false);
        jTextField_salescreatetotalamount.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatetotalamount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatetotalamount.setForeground(new java.awt.Color(0, 0, 150));
        jTextField_salescreatetotalamount.setText("0.00");
        jTextField_salescreatetotalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton_salescreatecancel.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreatecancel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreatecancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreatecancel.setText("CANCEL");
        jButton_salescreatecancel.setAlignmentY(0.0F);
        jButton_salescreatecancel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreatecancel.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_salescreatecancel.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_salescreatecancel.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_salescreatecancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreatecancelActionPerformed(evt);
            }
        });

        jTable_salescreate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable_salescreate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SERIAL NO", "MEDICINE ID", "MEDICINE NAME", "UNIT", "RATE", "QUANTITY", "PRICE", "DISCOUNT", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_salescreate.setSelectionBackground(new java.awt.Color(45, 120, 230));
        jTable_salescreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_salescreateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_salescreate);

        jButton_salescreateprint.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreateprint.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreateprint.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreateprint.setText("PRINT");
        jButton_salescreateprint.setAlignmentY(0.0F);
        jButton_salescreateprint.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreateprint.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_salescreateprint.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_salescreateprint.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_salescreateprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreateprintActionPerformed(evt);
            }
        });

        jButton_salescreatesave.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salescreatesave.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salescreatesave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salescreatesave.setText("SAVE");
        jButton_salescreatesave.setAlignmentY(0.0F);
        jButton_salescreatesave.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salescreatesave.setMaximumSize(new java.awt.Dimension(100, 35));
        jButton_salescreatesave.setMinimumSize(new java.awt.Dimension(100, 35));
        jButton_salescreatesave.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton_salescreatesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salescreatesaveActionPerformed(evt);
            }
        });

        jTextField_salescreatestock.setEditable(false);
        jTextField_salescreatestock.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_salescreatestock.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salescreatestock.setForeground(new java.awt.Color(100, 100, 100));
        jTextField_salescreatestock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salescreatestock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salescreatestockKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Stock");

        javax.swing.GroupLayout jPanel_salescreateLayout = new javax.swing.GroupLayout(jPanel_salescreate);
        jPanel_salescreate.setLayout(jPanel_salescreateLayout);
        jPanel_salescreateLayout.setHorizontalGroup(
            jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salescreateLayout.createSequentialGroup()
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                        .addComponent(jButton_salescreateadd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_salescreatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_salescreateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_salescreatedelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_salescreatesalesunit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_salescreateprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_salescreatetotaldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salescreateLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextField_salescreatesalesprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_salescreatediscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField_salescreatepatientid, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_salescreateid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                        .addComponent(jTextField_salescreatemedicineid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_salescreateamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_salescreateLayout.createSequentialGroup()
                                        .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_salescreatemedicinename, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField_salescreatepatientname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                    .addComponent(jTextField_salescreatedate))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_salescreatestock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_salescreatequantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel_salescreateLayout.createSequentialGroup()
                                .addComponent(jTextField_salescreatetotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_salescreatenetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salescreateLayout.createSequentialGroup()
                .addComponent(jButton_salescreatesave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_salescreateprint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_salescreatecancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salescreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_salescreateLayout.setVerticalGroup(
            jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salescreateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_salescreateid)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_salescreatedate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_salescreatepatientid)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_salescreatepatientname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatemedicineid)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_salescreatemedicinename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatesalesunit)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatequantity)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatesalesprice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_salescreatestock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_salescreateprice)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_salescreateamount))
                    .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_salescreatediscount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_salescreatedelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salescreateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salescreatereset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salescreateadd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatenetamount)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatetotaldiscount)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salescreatetotalamount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_salescreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_salescreatecancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salescreateprint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salescreatesave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("CREATE SALES", jPanel_salescreate);

        jPanel_salesview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_salesview.setMaximumSize(new java.awt.Dimension(1180, 680));
        jPanel_salesview.setMinimumSize(new java.awt.Dimension(1180, 680));
        jPanel_salesview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_salesviewMouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel31.setText("Enter keyword");

        jTextField_salesviewenterkey.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_salesviewenterkey.setForeground(new java.awt.Color(50, 50, 50));
        jTextField_salesviewenterkey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField_salesviewenterkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_salesviewenterkeyKeyReleased(evt);
            }
        });

        jTable_salesview.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable_salesview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE", "PATIENT NAME", "AMOUNT", "DISCOUNT", "NET AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_salesview.setSelectionBackground(new java.awt.Color(45, 120, 230));
        jScrollPane2.setViewportView(jTable_salesview);

        jButton_salesviewdelete.setBackground(new java.awt.Color(45, 120, 230));
        jButton_salesviewdelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_salesviewdelete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salesviewdelete.setText("DELETE");
        jButton_salesviewdelete.setAlignmentY(0.0F);
        jButton_salesviewdelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 120, 230), 3)));
        jButton_salesviewdelete.setMaximumSize(new java.awt.Dimension(85, 35));
        jButton_salesviewdelete.setMinimumSize(new java.awt.Dimension(85, 35));
        jButton_salesviewdelete.setPreferredSize(new java.awt.Dimension(85, 35));
        jButton_salesviewdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salesviewdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_salesviewLayout = new javax.swing.GroupLayout(jPanel_salesview);
        jPanel_salesview.setLayout(jPanel_salesviewLayout);
        jPanel_salesviewLayout.setHorizontalGroup(
            jPanel_salesviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salesviewLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_salesviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel_salesviewLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_salesviewenterkey, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 632, Short.MAX_VALUE)
                        .addComponent(jButton_salesviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel_salesviewLayout.setVerticalGroup(
            jPanel_salesviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_salesviewLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_salesviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_salesviewenterkey)
                    .addComponent(jButton_salesviewdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("  VIEW SALES  ", jPanel_salesview);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1180, 670));

        jLabel_salesclose.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        jLabel_salesclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_salesclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salesclose.setText("X");
        jLabel_salesclose.setAlignmentY(0.0F);
        jLabel_salesclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salescloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_salesclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1200, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    MysqlConnection mc = new MysqlConnection();
    
    public void genId(){
        //SA000000
        try{
            ResultSet rs = mc.getData("SELECT id FROM sales ORDER BY id DESC LIMIT 1");
		if(rs.next()){
			String idval = rs.getString("id");
			int ln = idval.length();
			String stxt = idval.substring(0, 2);
			String snum = idval.substring(2, ln);
                        String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
			sid = stxt + num;
		}
		else{
			sid = "SA000001";
		}
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }
    
    public void setId(){
        int ln = sid.length();
        String stxt = sid.substring(0, 2);
	String snum = sid.substring(2, ln);
	String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
	nxtsid = stxt + num;
    }
    
    public void genSalesItemId(){
        //SI000000
        try{
            ResultSet rs = mc.getData("SELECT id FROM sales_item ORDER BY id DESC LIMIT 1");
		if(rs.next()){
			String idval = rs.getString("id");
			int ln = idval.length();
			String stxt = idval.substring(0, 2);
			String snum = idval.substring(2, ln);
                        String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
			sitmid = stxt + num;
		}
		else{
			sitmid = "SI000001";
		}
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }
    
    public void currentDate(){
        Thread currentDate = new Thread(){
            public void run(){
                try{
                    for(;;){
                        Calendar clr = new GregorianCalendar();
                        int year = clr.get(Calendar.YEAR);
                        int month = clr.get(Calendar.MONTH);
                        month++; 
                        int day = clr.get(Calendar.DAY_OF_MONTH);
                        int hour = clr.get(Calendar.HOUR);
                        int minute = clr.get(Calendar.MINUTE);
                        int second = clr.get(Calendar.SECOND);
                        String syear = String.format("%04d", year);
                        String smonth = String.format("%02d", month);
                        String sday = String.format("%02d", day);
                        String shour = String.format("%02d", hour);
                        String sminute = String.format("%02d", minute);
                        String ssecond = String.format("%02d", second);
                        jTextField_salescreatedate.setText(syear + "-" + smonth + "-" + sday + " " + shour + ":" + sminute + ":" + ssecond);
                        sleep(1000);
                    }
                }
                catch(Exception exc){
                    exc.printStackTrace();
                }
            }
        };
        currentDate.start();
    }
    
    public void mediPrice(){
        if(!jTextField_salescreatesalesprice.getText().isEmpty()){
            salesprice = new BigDecimal(jTextField_salescreatesalesprice.getText());
        }
        else{
            mediprice = new BigDecimal("0.00");
        }
        if(!jTextField_salescreatequantity.getText().isEmpty()){
            mediqty = new BigDecimal(jTextField_salescreatequantity.getText());
        }
        else{
            mediqty = new BigDecimal("0.00");
        }
        mediprice = salesprice.multiply(mediqty);
        jTextField_salescreateprice.setText(String.format("%.2f", mediprice));
    }    
    
    public void mediAmount(){
        if(!jTextField_salescreateprice.getText().isEmpty()){
            price = new BigDecimal(jTextField_salescreateprice.getText());
        }
        else{
            price = new BigDecimal("0.00");
        }
        if(!jTextField_salescreatediscount.getText().isEmpty()){
            discount = new BigDecimal(jTextField_salescreatediscount.getText());
        }
        else{
            discount = new BigDecimal("0.00");
        }
        amount = price.subtract(discount);
        jTextField_salescreateamount.setText(String.format("%.2f", amount));
    }
       
    public void totalAmount(){
        int trc = jTable_salescreate.getRowCount();
        if(trc > 0){
            bdprz = new BigDecimal("0");
            for(int i = 0; i < trc; i++){
                bdprz = bdprz.add(new BigDecimal(jTable_salescreate.getValueAt(i, 6).toString()));
            }
            jTextField_salescreatetotalamount.setText(String.format("%.2f", bdprz));
        }
        else{
            jTextField_salescreatetotalamount.setText("0.00");
        }
    }
    
    public void totalDiscount(){
        int trc = jTable_salescreate.getRowCount();
        if(trc > 0){
            bddis = new BigDecimal("0");
            for(int i = 0; i < trc; i++){
                bddis = bddis.add(new BigDecimal(jTable_salescreate.getValueAt(i, 7).toString()));
            }
            jTextField_salescreatetotaldiscount.setText(String.format("%.2f", bddis));
        }
        else{
            jTextField_salescreatetotaldiscount.setText("0.00");
        }
    }
    
    public void salesNetAmount(){
        if(!jTextField_salescreatetotalamount.getText().isEmpty()){
            totalamount = new BigDecimal(jTextField_salescreatetotalamount.getText());
        }
        else{
            totalamount = new BigDecimal("0.00");
        }
        if(!jTextField_salescreatetotaldiscount.getText().isEmpty()){
            totaldiscount = new BigDecimal(jTextField_salescreatetotaldiscount.getText());
        }
        else{
            totaldiscount = new BigDecimal("0.00");
        }
        netamount = totalamount.subtract(totaldiscount);
        jTextField_salescreatenetamount.setText(String.format("%.2f", netamount));
    }
    
    public void stockMediQty(String salmediid, double salmediqty){
        try{
            this.salmediid = salmediid;
            this.salmediqty = salmediqty;
            ResultSet rs = mc.getData("SELECT quantity FROM medicine WHERE medicine.id = '"+this.salmediid+"'");
            if(rs.next()){
                stmediqty = rs.getDouble("quantity") - this.salmediqty;
            }            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    public void stockMediQtyDeleteSales(String salmediid, double salmediqty){
        try{
            this.salmediid = salmediid;
            this.salmediqty = salmediqty;
            ResultSet rs = mc.getData("SELECT quantity FROM medicine WHERE medicine.id = '"+this.salmediid+"'");
            if(rs.next()){
                stmediqty = rs.getDouble("quantity") + this.salmediqty;
            }            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }    
    
    private void jLabel_salescloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salescloseMouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel_salescloseMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jTextField_salescreatepatientidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatepatientidKeyPressed
        jTextField_salescreatepatientname.setText(null);
    }//GEN-LAST:event_jTextField_salescreatepatientidKeyPressed

    private void jTextField_salescreatepatientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatepatientidKeyReleased
        try{
            ResultSet rs = mc.getData("SELECT name FROM patient WHERE id = '"+jTextField_salescreatepatientid.getText()+"'");
            if(rs.first()){
                jTextField_salescreatepatientname.setText(rs.getString("name"));
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
    }//GEN-LAST:event_jTextField_salescreatepatientidKeyReleased

    private void jTextField_salescreatemedicineidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatemedicineidKeyPressed
        jTextField_salescreatemedicinename.setText(null);
        jTextField_salescreatesalesunit.setText(null);
        jTextField_salescreatesalesprice.setText(null);
        jTextField_salescreatestock.setText(null);
        jTextField_salescreatequantity.setText("0.00");
        jTextField_salescreateprice.setText(null);
        jTextField_salescreatediscount.setText("0.00");
        jTextField_salescreateamount.setText("0.00");
    }//GEN-LAST:event_jTextField_salescreatemedicineidKeyPressed

    private void jTextField_salescreatemedicineidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatemedicineidKeyReleased
        try{
            ResultSet rs = mc.getData("SELECT name, sales_unit, sales_price, quantity FROM medicine WHERE id = '"+jTextField_salescreatemedicineid.getText()+"'");
            if(rs.first()){
                jTextField_salescreatemedicinename.setText(rs.getString("name"));
                jTextField_salescreatesalesunit.setText(rs.getString("sales_unit"));
                jTextField_salescreatesalesprice.setText(rs.getString("sales_price"));
                jTextField_salescreatestock.setText(rs.getString("quantity"));
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}
        
        if(!jTextField_salescreatesalesprice.getText().isEmpty() && !jTextField_salescreatequantity.getText().isEmpty()){
            mediPrice();
            mediAmount();
        }
        /*else{
            totalamount = new BigDecimal("0.00");
        }*/ 
    }//GEN-LAST:event_jTextField_salescreatemedicineidKeyReleased

    private void jTextField_salescreatequantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatequantityKeyReleased
        try{
            if(!jTextField_salescreatequantity.getText().isEmpty()){
                if(Double.parseDouble(jTextField_salescreatequantity.getText()) > Double.parseDouble(jTextField_salescreatestock.getText())){
                    JOptionPane.showMessageDialog(null, "Out of stock. Please try lesser quantity!");
                    jTextField_salescreatequantity.setText("0.00");
                }
                else{
                    mediPrice();
                    mediAmount();
                }
            }
            else{
                jTextField_salescreatequantity.setText("0.00");
            }
	}
	catch(Exception exc){
		JOptionPane.showMessageDialog(null, exc);
	}  
    }//GEN-LAST:event_jTextField_salescreatequantityKeyReleased

    private void jTextField_salescreatediscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatediscountKeyReleased
        mediAmount();
    }//GEN-LAST:event_jTextField_salescreatediscountKeyReleased

    private void jButton_salescreateaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreateaddActionPerformed
        if(jTextField_salescreatepatientid.getText().isEmpty() || jTextField_salescreatepatientname.getText().isEmpty() || jTextField_salescreatemedicineid.getText().isEmpty() || jTextField_salescreatemedicinename.getText().isEmpty() || jTextField_salescreatesalesunit.getText().isEmpty() || jTextField_salescreatesalesprice.getText().isEmpty() || jTextField_salescreatequantity.getText().isEmpty() || jTextField_salescreateprice.getText().isEmpty() || jTextField_salescreatediscount.getText().isEmpty() || jTextField_salescreateamount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
            dtm.addRow(new Object[]{sitmid, jTextField_salescreatemedicineid.getText(), jTextField_salescreatemedicinename.getText(), jTextField_salescreatesalesunit.getText(), jTextField_salescreatesalesprice.getText(), jTextField_salescreatequantity.getText(), jTextField_salescreateprice.getText(), jTextField_salescreatediscount.getText(), jTextField_salescreateamount.getText()});
            jTextField_salescreatemedicineid.setText(null);
            jTextField_salescreatemedicinename.setText(null);
            jTextField_salescreatesalesunit.setText(null);
            jTextField_salescreatesalesprice.setText(null);
            jTextField_salescreatestock.setText(null);
            jTextField_salescreatequantity.setText("0.00");
            jTextField_salescreateprice.setText(null);
            jTextField_salescreatediscount.setText("0.00");
            jTextField_salescreateamount.setText("0.00");
            
            int ln = sitmid.length();
            String stxt = sitmid.substring(0, 2);
            String snum = sitmid.substring(2, ln);
            String num = String.format("%0" + snum.length() + "d", Integer.parseInt(snum) + 1);
            sitmid = stxt + num;
        }
        totalAmount();
        totalDiscount();
        salesNetAmount();
    }//GEN-LAST:event_jButton_salescreateaddActionPerformed

    private void jButton_salescreateresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreateresetActionPerformed
        jTextField_salescreatepatientid.setText(null);
        jTextField_salescreatepatientname.setText(null);
        jTextField_salescreatemedicineid.setText(null);
        jTextField_salescreatemedicinename.setText(null);
        jTextField_salescreatesalesunit.setText(null);
        jTextField_salescreatesalesprice.setText(null);
        jTextField_salescreatestock.setText(null);
        jTextField_salescreatequantity.setText("0.00");
        jTextField_salescreateprice.setText(null);
        jTextField_salescreatediscount.setText("0.00");
        jTextField_salescreateamount.setText("0.00");
    }//GEN-LAST:event_jButton_salescreateresetActionPerformed

    private void jButton_salescreateupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreateupdateActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        int sri[] = jTable_salescreate.getSelectedRows();
        if(sri.length == 1){
            if(jTextField_salescreatepatientid.getText().isEmpty() || jTextField_salescreatepatientname.getText().isEmpty() || jTextField_salescreatemedicineid.getText().isEmpty() || jTextField_salescreatemedicinename.getText().isEmpty() || jTextField_salescreatesalesunit.getText().isEmpty() || jTextField_salescreatesalesprice.getText().isEmpty() || jTextField_salescreatequantity.getText().isEmpty() || jTextField_salescreateprice.getText().isEmpty() || jTextField_salescreatediscount.getText().isEmpty() || jTextField_salescreateamount.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill all fields!");
            }
            else{
                dtm.setValueAt(jTextField_salescreatemedicineid.getText(), sri[0], 1);
                dtm.setValueAt(jTextField_salescreatemedicinename.getText(), sri[0], 2);
                dtm.setValueAt(jTextField_salescreatesalesunit.getText(), sri[0], 3);
                dtm.setValueAt(jTextField_salescreatesalesprice.getText(), sri[0], 4);
                dtm.setValueAt(jTextField_salescreatequantity.getText(), sri[0], 5);
                dtm.setValueAt(jTextField_salescreateprice.getText(), sri[0], 6);
                dtm.setValueAt(jTextField_salescreatediscount.getText(), sri[0], 7);
                dtm.setValueAt(jTextField_salescreateamount.getText(), sri[0], 8);
                jTextField_salescreatemedicineid.setText(null);
                jTextField_salescreatemedicinename.setText(null);
                jTextField_salescreatesalesunit.setText(null);
                jTextField_salescreatesalesprice.setText(null);
                jTextField_salescreatestock.setText(null);
                jTextField_salescreatequantity.setText("0.00");
                jTextField_salescreateprice.setText(null);
                jTextField_salescreatediscount.setText("0.00");
                jTextField_salescreateamount.setText("0.00");
                jTable_salescreate.clearSelection();
                jButton_salescreateadd.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to update!");
        }        
    totalAmount();
    totalDiscount();
    salesNetAmount();
    }//GEN-LAST:event_jButton_salescreateupdateActionPerformed

    private void jTable_salescreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_salescreateMouseClicked
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        int sri[] = jTable_salescreate.getSelectedRows();
        if(sri.length == 1){
            jButton_salescreateadd.setEnabled(false);
            jTextField_salescreatemedicineid.setText(dtm.getValueAt(sri[0], 1).toString());
            jTextField_salescreatemedicinename.setText(dtm.getValueAt(sri[0], 2).toString());
            jTextField_salescreatesalesunit.setText(dtm.getValueAt(sri[0], 3).toString());
            jTextField_salescreatesalesprice.setText(dtm.getValueAt(sri[0], 4).toString());
            jTextField_salescreatequantity.setText(dtm.getValueAt(sri[0], 5).toString());
            jTextField_salescreateprice.setText(dtm.getValueAt(sri[0], 6).toString());
            jTextField_salescreatediscount.setText(dtm.getValueAt(sri[0], 7).toString());
            jTextField_salescreateamount.setText(dtm.getValueAt(sri[0], 8).toString());
        }
        else{
            jTextField_salescreatemedicineid.setText(null);
            jTextField_salescreatemedicinename.setText(null);
            jTextField_salescreatesalesunit.setText(null);
            jTextField_salescreatesalesprice.setText(null);
            jTextField_salescreatequantity.setText("0.00");
            jTextField_salescreateprice.setText(null);
            jTextField_salescreatediscount.setText("0.00");
            jTextField_salescreateamount.setText("0.00");
        }
    }//GEN-LAST:event_jTable_salescreateMouseClicked

    private void jPanel_salescreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_salescreateMouseClicked
        jTable_salescreate.clearSelection();
        if(!jButton_salescreateadd.isEnabled()){
            jButton_salescreateadd.setEnabled(true);
            jTextField_salescreatemedicineid.setText(null);
            jTextField_salescreatemedicinename.setText(null);
            jTextField_salescreatesalesunit.setText(null);
            jTextField_salescreatesalesprice.setText(null);
            jTextField_salescreatequantity.setText("0.00");
            jTextField_salescreateprice.setText(null);
            jTextField_salescreatediscount.setText("0.00");
            jTextField_salescreateamount.setText("0.00");
        }
    }//GEN-LAST:event_jPanel_salescreateMouseClicked

    private void jButton_salescreatedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreatedeleteActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        int sri[] = jTable_salescreate.getSelectedRows();
        if(sri.length > 0){
            for(int i = sri.length - 1; i >= 0; i--){
                    dtm.removeRow(sri[i]);
            }
            jTextField_salescreatemedicineid.setText(null);
            jTextField_salescreatemedicinename.setText(null);
            jTextField_salescreatesalesunit.setText(null);
            jTextField_salescreatesalesprice.setText(null);
            jTextField_salescreatestock.setText(null);
            jTextField_salescreatequantity.setText("0.00");
            jTextField_salescreateprice.setText(null);
            jTextField_salescreatediscount.setText("0.00");
            jTextField_salescreateamount.setText("0.00");
            jButton_salescreateadd.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to delete!");
        }
        totalAmount();
        totalDiscount();
        salesNetAmount();
    }//GEN-LAST:event_jButton_salescreatedeleteActionPerformed

    private void jButton_salescreatesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreatesaveActionPerformed
        int trc = jTable_salescreate.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        if(trc > 0){
            try{
                genId();
                setId();
                mc.putData("INSERT INTO sales (id, patient, amount, discount, net_amount, date) VALUES ('"+sid+"', '"+jTextField_salescreatepatientid.getText()+"', '"+jTextField_salescreatetotalamount.getText()+"', '"+jTextField_salescreatetotaldiscount.getText()+"', '"+jTextField_salescreatenetamount.getText()+"', '"+jTextField_salescreatedate.getText()+"')");
                for(int i = 0; i < trc; i++){
                    Statement stmt = MysqlConnection.conn().createStatement();
                    stmt.executeUpdate("INSERT INTO sales_item (id, sales, medicine, quantity, price, discount, amount) VALUES ('"+jTable_salescreate.getValueAt(i, 0).toString()+"', '"+sid+"', '"+jTable_salescreate.getValueAt(i, 1).toString()+"', '"+jTable_salescreate.getValueAt(i, 5).toString()+"', '"+jTable_salescreate.getValueAt(i, 6).toString()+"', '"+jTable_salescreate.getValueAt(i, 7).toString()+"', '"+jTable_salescreate.getValueAt(i, 8).toString()+"')");
                    stockMediQty(jTable_salescreate.getValueAt(i, 1).toString(), Double.parseDouble(jTable_salescreate.getValueAt(i, 5).toString()));
                    stmt.executeUpdate("UPDATE medicine SET quantity = '"+String.format("%.2f", stmediqty)+"' WHERE id = '"+jTable_salescreate.getValueAt(i, 1).toString()+"'");
                }
                dtm.setRowCount(0);
                jTextField_salescreateid.setText(nxtsid);
                jTextField_salescreatepatientid.setText(null);
                jTextField_salescreatepatientname.setText(null);
                jTextField_salescreatemedicineid.setText(null);
                jTextField_salescreatemedicinename.setText(null);
                jTextField_salescreatesalesunit.setText(null);
                jTextField_salescreatesalesprice.setText(null);
                jTextField_salescreatestock.setText(null);
                jTextField_salescreatequantity.setText("0.00");
                jTextField_salescreateprice.setText(null);
                jTextField_salescreatediscount.setText("0.00");
                jTextField_salescreateamount.setText("0.00");
                jTextField_salescreatetotalamount.setText("0.00");
                jTextField_salescreatetotaldiscount.setText("0.00");
                jTextField_salescreatenetamount.setText("0.00");
                JOptionPane.showMessageDialog(null, "DONE!");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "There is NO data to SAVE!");
        }
        DefaultTableModel dtmv = (DefaultTableModel)jTable_salesview.getModel();
        dtmv.setRowCount(0);
        loadTbl();
    }//GEN-LAST:event_jButton_salescreatesaveActionPerformed

    private void jPanel_salesviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_salesviewMouseClicked
        jTable_salesview.clearSelection();
    }//GEN-LAST:event_jPanel_salesviewMouseClicked

    private void jTextField_salesviewenterkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salesviewenterkeyKeyReleased
        DefaultTableModel dtmv = (DefaultTableModel)jTable_salesview.getModel();
        String search = jTextField_salesviewenterkey.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(dtmv);
        jTable_salesview.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField_salesviewenterkeyKeyReleased

    private void jButton_salesviewdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salesviewdeleteActionPerformed
        int sri[] = jTable_salesview.getSelectedRows();
        String sri_id[] = new String[sri.length];
        DefaultTableModel dtm = (DefaultTableModel)jTable_salesview.getModel();
        if(sri.length > 0){
            try{
                for(int i = sri.length - 1; i >= 0; i--){
                    sri_id[i] = jTable_salesview.getModel().getValueAt(sri[i], 0).toString();
                    Statement stmt = MysqlConnection.conn().createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT sales_item.medicine, sales_item.quantity FROM sales_item WHERE sales_item.sales = '"+sri_id[i]+"'");
                    while(rs.next()){
                        stockMediQtyDeleteSales(rs.getString("sales_item.medicine"), Double.parseDouble(rs.getString("sales_item.quantity")));
                        stmt.executeUpdate("UPDATE medicine SET quantity = '"+String.format("%.2f", stmediqty)+"' WHERE id = '"+rs.getString("sales_item.medicine")+"'");                        
                    }
                    stmt.executeUpdate("DELETE FROM sales_item WHERE sales_item.sales = '"+sri_id[i]+"'");
                    stmt.executeUpdate("DELETE FROM sales WHERE sales.id = '"+sri_id[i]+"'");                    
                    dtm.removeRow(sri[i]);
                }
                dtm.setRowCount(0);
                loadTbl();
                JOptionPane.showMessageDialog(null, "Data deleted successfully!");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select the row to delete data!");
        }
    }//GEN-LAST:event_jButton_salesviewdeleteActionPerformed

    private void jButton_salescreateprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreateprintActionPerformed
        int trc = jTable_salescreate.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        if(trc > 0){
            try{
                genId();
                setId();
                mc.putData("INSERT INTO sales (id, patient, amount, discount, net_amount, date) VALUES ('"+sid+"', '"+jTextField_salescreatepatientid.getText()+"', '"+jTextField_salescreatetotalamount.getText()+"', '"+jTextField_salescreatetotaldiscount.getText()+"', '"+jTextField_salescreatenetamount.getText()+"', '"+jTextField_salescreatedate.getText()+"')");
                for(int i = 0; i < trc; i++){
                    Statement stmt = MysqlConnection.conn().createStatement();
                    stmt.executeUpdate("INSERT INTO sales_item (id, sales, medicine, quantity, price, discount, amount) VALUES ('"+jTable_salescreate.getValueAt(i, 0).toString()+"', '"+sid+"', '"+jTable_salescreate.getValueAt(i, 1).toString()+"', '"+jTable_salescreate.getValueAt(i, 5).toString()+"', '"+jTable_salescreate.getValueAt(i, 6).toString()+"', '"+jTable_salescreate.getValueAt(i, 7).toString()+"', '"+jTable_salescreate.getValueAt(i, 8).toString()+"')");
                    stockMediQty(jTable_salescreate.getValueAt(i, 1).toString(), Double.parseDouble(jTable_salescreate.getValueAt(i, 5).toString()));
                    stmt.executeUpdate("UPDATE medicine SET quantity = '"+String.format("%.2f", stmediqty)+"' WHERE id = '"+jTable_salescreate.getValueAt(i, 1).toString()+"'");
                }
                dtm.setRowCount(0);
                jTextField_salescreateid.setText(nxtsid);
                jTextField_salescreatepatientid.setText(null);
                jTextField_salescreatepatientname.setText(null);
                jTextField_salescreatemedicineid.setText(null);
                jTextField_salescreatemedicinename.setText(null);
                jTextField_salescreatesalesunit.setText(null);
                jTextField_salescreatesalesprice.setText(null);
                jTextField_salescreatestock.setText(null);
                jTextField_salescreatequantity.setText("0.00");
                jTextField_salescreateprice.setText(null);
                jTextField_salescreatediscount.setText("0.00");
                jTextField_salescreateamount.setText("0.00");
                jTextField_salescreatetotalamount.setText("0.00");
                jTextField_salescreatetotaldiscount.setText("0.00");
                jTextField_salescreatenetamount.setText("0.00");
                JOptionPane.showMessageDialog(null, "DONE!");
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "There is no data to print!");
        }
        DefaultTableModel dtmv = (DefaultTableModel)jTable_salesview.getModel();
        dtmv.setRowCount(0);
        loadTbl();
        
        //PRINT
    }//GEN-LAST:event_jButton_salescreateprintActionPerformed

    private void jButton_salescreatecancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salescreatecancelActionPerformed
        jTextField_salescreatepatientid.setText(null);
        jTextField_salescreatepatientname.setText(null);
        jTextField_salescreatemedicineid.setText(null);
        jTextField_salescreatemedicinename.setText(null);
        jTextField_salescreatesalesunit.setText(null);
        jTextField_salescreatesalesprice.setText(null);
        jTextField_salescreatestock.setText(null);
        jTextField_salescreatequantity.setText("0.00");
        jTextField_salescreateprice.setText(null);
        jTextField_salescreatediscount.setText("0.00");
        jTextField_salescreateamount.setText("0.00");
        jTextField_salescreatetotalamount.setText("0.00");
        jTextField_salescreatetotaldiscount.setText("0.00");
        jTextField_salescreatenetamount.setText("0.00");
        DefaultTableModel dtm = (DefaultTableModel)jTable_salescreate.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_jButton_salescreatecancelActionPerformed

    private void jTextField_salescreatestockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_salescreatestockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_salescreatestockKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salescreateadd;
    private javax.swing.JButton jButton_salescreatecancel;
    private javax.swing.JButton jButton_salescreatedelete;
    private javax.swing.JButton jButton_salescreateprint;
    private javax.swing.JButton jButton_salescreatereset;
    private javax.swing.JButton jButton_salescreatesave;
    private javax.swing.JButton jButton_salescreateupdate;
    private javax.swing.JButton jButton_salesviewdelete;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_salesclose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_salescreate;
    private javax.swing.JPanel jPanel_salesview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_salescreate;
    private javax.swing.JTable jTable_salesview;
    private javax.swing.JTextField jTextField_salescreateamount;
    private javax.swing.JTextField jTextField_salescreatedate;
    private javax.swing.JTextField jTextField_salescreatediscount;
    private javax.swing.JTextField jTextField_salescreateid;
    private javax.swing.JTextField jTextField_salescreatemedicineid;
    private javax.swing.JTextField jTextField_salescreatemedicinename;
    private javax.swing.JTextField jTextField_salescreatenetamount;
    private javax.swing.JTextField jTextField_salescreatepatientid;
    private javax.swing.JTextField jTextField_salescreatepatientname;
    private javax.swing.JTextField jTextField_salescreateprice;
    private javax.swing.JTextField jTextField_salescreatequantity;
    private javax.swing.JTextField jTextField_salescreatesalesprice;
    private javax.swing.JTextField jTextField_salescreatesalesunit;
    private javax.swing.JTextField jTextField_salescreatestock;
    private javax.swing.JTextField jTextField_salescreatetotalamount;
    private javax.swing.JTextField jTextField_salescreatetotaldiscount;
    private javax.swing.JTextField jTextField_salesviewenterkey;
    // End of variables declaration//GEN-END:variables

    private void loadTbl(){
        try{
            DefaultTableModel dtm = (DefaultTableModel)jTable_salesview.getModel();
            ResultSet rs = mc.getData("SELECT sales.id, patient.name, sales.amount, sales.discount, sales.net_amount, sales.date FROM sales, patient WHERE sales.patient = patient.id");
            while(rs.next()){
                Vector vtr = new Vector();
                vtr.add(rs.getString("sales.id"));
                vtr.add(rs.getString("sales.date"));
                vtr.add(rs.getString("patient.name"));
                vtr.add(rs.getString("sales.amount"));
                vtr.add(rs.getString("sales.discount"));
                vtr.add(rs.getString("sales.net_amount"));
                dtm.addRow(vtr);
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
